### ISSUE TITLE
Multithreading/Monothreading

### ISSUE THREAD

**Issue by mpdn** [SRombauts/SQLiteCpp#1]
In the TODO.txt, it is claimed the library isn't thread safe, but is there any reason for that to be the case? "Threadsafe" in the context of SQLite means you can open multiple connections in different threads, not that you can use a single connection in multiple threads, so I don't see any reason why this shouldn't be threadsafe if the underlying SQLite implementation is threadsafe.

**Comment by ScottKaiGu** [comment]
i encounter a lot of #define SQLITE_BUSY         5   errors.
is there any recommended way to use SQLiteCpp in a Multithread environment?

**Comment by SRombauts** [comment]
Use Database::setBusyTimeout() on each newly opened connection with a not null value in ms so that SQLite will retry in case of contention between multiple threads.
