### ISSUE TITLE
Using the library out of the box: manual

### ISSUE THREAD

**Issue by amigo421** [SRombauts/SQLiteCpp#105]
I've just tried to perform first time build the library with my project using usual cmake way: 

```
cmake_minimum_required(VERSION 3.0)
include(ExternalProject)
find_package(Git REQUIRED)

set(EXTERNAL_INSTALL_LOCATION ${CMAKE_BINARY_DIR}/external)

ExternalProject_Add(SQLiteCpp
    GIT_REPOSITORY https://github.com/SRombauts/SQLiteCpp.git
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION}
)

```

and 

`include(AddSQLiteCpp)`

and got a couple of the errors:

> Scanning dependencies of target SQLiteCpp_cpplint
> NMAKE : fatal error U1077: 'C:\dev\tools\Python36\python.exe' : return code '0x1'

any idea? does it require 2.7? (of course, I've disabled this temporary by adding cmake_args but i'd prefer to understand why it is there)

next one something like "no install step provided" , etc.
that is enough clear, and my current externa project for the getting SQLiteCPP looks like:

set(EXTERNAL_INSTALL_LOCATION ${CMAKE_BINARY_DIR}/external)

```
ExternalProject_Add(SQLiteCpp
    GIT_REPOSITORY https://github.com/SRombauts/SQLiteCpp.git
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION} -DSQLITECPP_RUN_CPPLINT=OFF
    GIT_TAG master
    TIMEOUT 10
    UPDATE_COMMAND ${GIT_EXECUTABLE} pull
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND ""
    LOG_DOWNLOAD ON
)

```

but could you provide your version of some <GetSQLiteCpp.cmake > for the just include(GetSQLiteCpp) into the project and quick start with the library ?

thank you

**Comment by SRombauts** [comment]
Please, have a look at #101 Help build a basic example
