### ISSUE TITLE
Is it possible to store a blob of unsigned integers?

### ISSUE THREAD

**Issue by timrae** [SRombauts/SQLiteCpp#109]
I have some data of type `vector<uint8_t>` that I want to store as a blob in an sqilte database. Unfortunately there's no interface for this... Is it simple enough to add?

`statement.bindNoCopy(2, my_vector.data());`

`error: invalid conversion from ‘unsigned char*’ to ‘const char*’`

```
In file included from ./build/tmp/include/SQLiteCpp/Column.h:13:0,
                 from ./build/tmp/include/SQLiteCpp/Database.h:13,
                 from./src/message_store.cpp:5:
./build/tmp/include/SQLiteCpp/Statement.h:155:10:note:   initializing argument 2 of ‘void SQLite::Statement::bindNoCopy(int, const char*)’
     void bindNoCopy(const int aIndex, const char*           apValue);
```

**Comment by SRombauts** [comment]
Hi @timrae, yes, there is a blob APIs.

You should use the following method:
    void Statement::bindNoCopy(const int aIndex, const void* apValue, const int aSize);

which would be something like:
    statement.bindNoCopy(2, my_vector.data(), my_vector.data().size());

but you should probably add an explicit cast like that:
    statement.bindNoCopy(2, static_cast<const void*>(my_vector.data()), my_vector.data().size());

Let me know if it's working,
Cheers!

**Comment by timrae** [comment]
Ooops, sorry I didn't see that, it's kind of obvious now that it shouldn't have worked without the size! The code is compiling now, thanks.

```c++
but you should probably add an explicit cast like that:
statement.bindNoCopy(2, static_cast<const void*>(my_vector.data()), my_vector.data().size());
```

Why do you suggest explicitly casting to `const void*`?

**Comment by SRombauts** [comment]
The method is asking for à buffer of void* so some compilers with high level of warnings will complain if you give char*
