### ISSUE TITLE
Can statement::bind() throw an exception?

### ISSUE THREAD

**Issue by timrae** [SRombauts/SQLiteCpp#110]
I couldn't see any exceptions explicitly thrown in the bind code in `Statement `, but it also doesn't say `noexcept` like some of the other functions. Is it safe to call `bind()` on a statement without catching `SQLite::Exception`?

**Comment by SRombauts** [comment]
No, sorry byt any Statement::bind() method can throw in case of a sqlite3_bind_xxx() error
