### ISSUE TITLE
Unable to install in VC++ 2015 Community

### ISSUE THREAD

**Issue by sinall** [SRombauts/SQLiteCpp#115]
Error Message:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Could not install package 'SQLiteCpp 1.1.1'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by SRombauts** [comment]
Hi @sinall, thanks for reporting, but I don't know anything about the package installation you are talking about.
Is this a MSVC nuget package or something like that?

**Comment by ha0x7c7** [comment]
@SRombauts  I guess he is talking about this https://www.nuget.org/packages/SQLiteCpp/

I have difficulty in using this library inside my own project which is a basic windows console application, I cloned the repository and ran the `build.bat` file, folder named build was created with a solution, I don't know how to use this generated solution in my own project.

Regards.

**Comment by SRombauts** [comment]
build.bat is only to help develop the SQLiteCpp library itself.

If you need to use the library into your project, you should probably integrate it using CMake, or you can copy the src/ and include/ files directly into your project if you prefer this.

=> Please have a look at the README.md, and at the https://github.com/SRombauts/SQLiteCpp_Example example project
