### ISSUE TITLE
Problem with bind 

### ISSUE THREAD

**Issue by kenenbek** [SRombauts/SQLiteCpp#124]
I have such query:
`mQuery(mDb, "SELECT * FROM bkk WHERE id in ( :LIST )"`

Everything is fine when I use:

```
        std::string s = "/lhcb/.rdst";
        mQuery.bind(":LIST", LIST);
```
and I have some output.

Problem occurs when I want to use more values in `:LIST`:
```
        std::string s = "/lhcb/.rdst, /lhcb/.rdst";
        mQuery.bind(":LIST", LIST);
```
`mQuery.executeStep()` returns me a `false`. 
I tried different ways like:
```
std::string s = "'/lhcb/.rdst', '/lhcb/.rdst'";
or
std::string s = "\"/lhcb/.rdst\", \"/lhcb/.rdst\"";
```
But they gives a nothing. 
Is it a bug?

**Comment by SRombauts** [comment]
Sorry, the SQLite3 does not support binding a list of values at once, and I did not add this to the C++ wrapper myself.

If you see some clean way to do this, through templates for instance, please contribute this back.

Cheers!

**Comment by kenenbek** [comment]
Is `mDb.execAndGet(SELECT * FROM table WHERE id in ('ID1', 'ID2'))  ` not a solution here, because `execAndGet` can't return several rows?
