### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by 4brunu** [SRombauts/SQLiteCpp#131]
Hi, the last release was almost a year ago, and in the master branch there are some new features and bug fixes.
Would you consider creating a new release?
This is important to me, because in my team we prefer to checkout specific releases and not commit's directly.
Thanks

**Comment by SRombauts** [comment]
Yes, sure, you are right about this!

**Comment by SRombauts** [comment]
Wanted to update SQLite to 3.19 before the 2.1.0 release, so I hit issue #125

**Comment by 4brunu** [comment]
Makes sense fix that issue before the release

**Comment by SRombauts** [comment]
@4brunu let me know if the 2.1.0 release is working for you, I got it working for me but needed to use a new CMake variable SQLITE_USE_LEGACY_STRUCT that the user can set to enable a SQLITE_USE_LEGACY_STRUCT compile flag (OFF by default) to use with SQLite <3.19

**Comment by 4brunu** [comment]
@SRombauts It works for me, thanks!

**Comment by SRombauts** [comment]
Thanks!
