### ISSUE TITLE
Cannot bind long int value.

### ISSUE THREAD

**Issue by multiplemonomials** [SRombauts/SQLiteCpp#147]
Hi, I've been integrating your library into my Android app, and I really like it so far.  Much more straightforward than the SOCI library I was using.
I did run into one small error though, with the following code building for Android NDK.

```c++
int64_t foo = 4;
SQLiteCpp::Statement statement(db, "INSERT INTO foobar(foo) VALUES(:foo)); 
statement.bind(1, foo);
```
result:
```
g++: error: call of overloaded 'bind(int, long int&)' is ambiguous
     statement.bind(1, foo);
     ^
  note: candidates are:

  SQLiteCpp-2.2.0/include/SQLiteCpp/Statement.h:112:10: note: void SQLite::Statement::bind(int, int)
       void bind(const int aIndex, const int           aValue);
            ^
  SQLiteCpp-2.2.0/include/SQLiteCpp/Statement.h:116:10: note: void SQLite::Statement::bind(int, unsigned int)
       void bind(const int aIndex, const unsigned      aValue);
            ^
  SQLiteCpp-2.2.0/include/SQLiteCpp/Statement.h:120:10: note: void SQLite::Statement::bind(int, long long int)
       void bind(const int aIndex, const long long     aValue);
...and so on...
```

Once I add the missing `void bind(const int aIndex, const long int      aValue);` into SQLite::Statement, everything works great.  Could you add this function, or is there some reason why it doesn't exist?

**Comment by SRombauts** [comment]
Thanks for reporting this, I'll have a look at it!

**Comment by SRombauts** [comment]
Thanks again @multiplemonomials :)
Let me know if the provided fix is not working for you!
