### ISSUE TITLE
Statement parameter name suggestion

### ISSUE THREAD

**Issue by prsolucoes** [SRombauts/SQLiteCpp#153]
Hi,

First, thanks to your great library. I will use it in my mobile project and my tool EzoRed (ezored.com) to build cross-platform mobile apps.

I want suggest only a thing: If the user dont put the ":" in parameter name, it can be added on bind function, no?

Query:

```sql
select * from customer where name = :name
```

Instead of:

```cpp
.bind(":name", "Paulo")
```

```cpp
.bind("name", "Paulo")
```

You library:

```cpp
void bind(...)
{
    if param_name[0] != ':'
    {
        param_name = param_name + ':';
    }
}
```

Something like this.

What you think?

**Comment by SRombauts** [comment]
Thank you for suggesting this. I am very busy ATM, working on entirely other technologies, so I can't develop this kind of new features, sorry.
