### ISSUE TITLE
License problem check

### ISSUE THREAD

**Issue by prsolucoes** [SRombauts/SQLiteCpp#154]
Hi man,

Thanks for the awesome library.

I have downloaded the source and embedded it on my project:
https://github.com/ezored/dependency-sample/tree/master/build/source/thirdparty

I want know if it has any problem with license, because it was not modified, only copied to my library.

Thanks.

**Comment by SRombauts** [comment]
Hi @prsolucoes, thanks!

The MIT License is very liberal, you can do nearly what you want with the source code, you can modify it and sell your program, you don't owe me anything :)

Enjoy!
