### ISSUE TITLE
Misleading error message in exception from Statement::exec

### ISSUE THREAD

**Issue by alanbirtles** [SRombauts/SQLiteCpp#156]
If Statement::exec is executed with mbDone set to true then an exception is thrown with the correct error code SQLITE_MISUSE returned from tryExec but the error message is "not an error"

**Comment by SRombauts** [comment]
Good catch, thanks for reporting it!

**Comment by tiendq** [comment]
@alanbirtles How does it happen? Did you mention [this function](https://github.com/SRombauts/SQLiteCpp/blob/master/src/Statement.cpp#L257)?

**Comment by alanbirtles** [comment]
just execute a statement twice without resetting it
