### ISSUE TITLE
How to use encryption with this library?

### ISSUE THREAD

**Issue by ha0x7c7** [SRombauts/SQLiteCpp#158]
How can I use encryption with this library?

**Comment by StuartJohnsen** [comment]
Seconding this question, I'm trying to use SQLCipher with this via replacing the SQLite3.h / c amalgamation files but I'm having 0 luck figuring out where to go and am pretty stuck.


As an example, dropping in SQLite's 3.4.2 amalgamation files created via their standard recommendation gives me a whole bunch of errors of this nature:
```
[ 88%] Building C object sqlite3/CMakeFiles/sqlite3.dir/sqlite3.c.o
/Users/sj/Code/sandbox/vendor/SQLiteCpp/sqlite3/sqlite3.c:34726:42: error: use of undeclared identifier 'close'
  { "close",        (sqlite3_syscall_ptr)close,      0  },
```

**Comment by ha0x7c7** [comment]
here is how you can use encryption:
` SQLite::Database db(utf16_to_utf8(dbName), SQLite::OPEN_READWRITE);
	db.key(secretKey);
`

you must have a version of `sqlice.c` which has encryption in itself.
