### ISSUE TITLE
error: unrecognized command line option "-Wpedantic"

### ISSUE THREAD

**Issue by x-serializer** [SRombauts/SQLiteCpp#163]
OS:     Fedora7 x86
Compiler:     g++ 4.1.2

when i use "cmake --build .",it cause an error.
error: unrecognized command line option "-Wpedantic"

*******************
if i modify it to "-pedantic",it could run well in this os and compiler.

**Comment by SRombauts** [comment]
Good to know, thanks.
But I won't try to support such an old compiler, sorry.
