### ISSUE TITLE
Problem with sqlite3_load_extension

### ISSUE THREAD

**Issue by prsolucoes** [SRombauts/SQLiteCpp#165]
Hi,

Im getting this error:

![image](https://user-images.githubusercontent.com/395096/47743396-bfa30000-dc5d-11e8-93d7-c17d6ef4e8f8.png)

Im using latest stable version with latest macos version.

Thanks.

**Comment by tiendq** [comment]
Try to build with `SQLITECPP_INTERNAL_SQLITE` e.g.

`cmake -DSQLITECPP_INTERNAL_SQLITE=ON ..`

**Comment by SRombauts** [comment]
Yes, the problem is your where using an external SQLite3 library without the support for load extensions.
