### ISSUE TITLE
problem with SQLiteCpp-master/examples/example1/main.cpp

### ISSUE THREAD

**Issue by rjf12138** [SRombauts/SQLiteCpp#166]
operating system: Ubuntu 18.04.1 LTS

Running result:
SQlite3 version 3.20.1 (3.22.0)
SQliteC++ version 2.02.00
SQLite exception: unable to open database file

The database file cannot be found by the program. I find that the problem may be in the getExamplePath().
The \_\_FILE\_\_ under my system are returns the source file name instead of source file path

**Comment by SRombauts** [comment]
Can you share how you try to execute the example?

Just try under Windows and Linux; launching from build/ folder is working well, as well as from the root folder.
