### ISSUE TITLE
Best way to use SELECT IN with this library?

### ISSUE THREAD

**Issue by prsolucoes** [SRombauts/SQLiteCpp#173]
Hi,

Best way to use SELECT IN with this library?

I have a vector of string and want a way to use it into "SELECT * FROM table1 WHERE n_type IN (:values)", where ":values" bind is this vector.

There is any way to do it?

If don't have, there is any way that i can prevent injection when create on-hand query?

Thanks

**Comment by SRombauts** [comment]
No, there is no way to do that currently; this is only a thin C++ wrapper on top of the SQLite C API.
