### ISSUE TITLE
Is it safe to loop over results and update/select other statements for same connection?

### ISSUE THREAD

**Issue by IAmWebSA** [SRombauts/SQLiteCpp#175]
I would like to know if it is safe to call Statements in a more layered way like

	       SQLite::Transaction trans(*mDb);
               SQLite::Statement getQuery(*mDb, "SELECT * FROM XXXX");
               while (getQuery.executeStep() == true)
               {
					SQLite::Statement insQuery(*mDb, "INSERT INTO XXX2 VALUES (Null, :name, :id, 0)" );
					insQuery.bind(":name", getQuery.getColumn("NAME").getString());
					insQuery.bind(":id", getQuery.getColumn("Id").getInt());
					insQuery.exec();

					SQLite::Statement getQuerySS(*mDb, "SELECT * FROM AAAA");
					while (getQuerySS.executeStep() == true)
					{
						//do further stuff
					}
               }
               trans.commit();

Or  are there any sqlite_finalize / cleanup issues with it?
What is the best practice to iterate over many results and use them in a subcall? 

Regards

**Comment by SRombauts** [comment]
It's totally safe to use Statements like this, I have done it a lot.

Sorry for not answering previously!
