### ISSUE TITLE
error: conversion from 'SQLite::Column' to 'unsigned char' is ambiguous

### ISSUE THREAD

**Issue by KOLANICH** [SRombauts/SQLiteCpp#179]

**Comment by SRombauts** [comment]
True, I did not provide conversion to char, short, unsigned char and unsigned short.

Not sure it's a good idea though, since this might imply a truncation. Though it could be true with other implicit cast I wrote, so why not....

Do you really use this kind of variable types?

**Comment by KOLANICH** [comment]
>Do you really use this kind of variable types?

I do.
