### ISSUE TITLE
conversion from 'SQLite::Column' to 'const short unsigned int' is ambiguous

### ISSUE THREAD

**Issue by KOLANICH** [SRombauts/SQLiteCpp#180]

**Comment by bstaletic** [comment]
Actually every unsigned integral except `unsigned int` when one tres to do `uintXX_t result = statement.getColumn(0)`, but the solution that works is just being explicit - `uintXX_t result = statement.getColumn(0).getInt()`.

**Comment by SRombauts** [comment]
Implemented with #179 a few hours ago :)
