### ISSUE TITLE
Doxygen documentation warning

### ISSUE THREAD

**Issue by kartikkumar** [SRombauts/SQLiteCpp#185]
Not sure if this warning is only appearing on my side when I compile, but just thought I'd report it in case it isn't.

```
/SQLiteCpp/include/SQLiteCpp/Database.h(160): warning: argument 'aBusyTimeoutMs' from the argument list of SQLite::Database::setBusyTimeout has muliple @param documentation sections
```

If I clear my backlog of tasks, I'll take a look myself and see if I can solve it and create a PR.

**Comment by SRombauts** [comment]
Mm, no, it's not appearing on my side
