### ISSUE TITLE
Unit test suite

### ISSUE THREAD

**Issue by kartikkumar** [SRombauts/SQLiteCpp#2]
Hi,

Firstly, nice looking library! Forked it and created a config file for CMake to play around with deploying it in some of my research projects.

One thing I noticed is that I can't seem to spot any unit tests that ship with the code, and I believe you've listed that as one of the goals for the library in the readme file.

Do you happen to have any unit tests written that demonstrate how the code implements RAII fully?

Thanks,

Kartik

**Comment by SRombauts** [comment]
Unit Test Suite still not perfect but now good enough for v1.0.0 release

**Comment by kartikkumar** [comment]
@SRombauts yep, good work! The unit test suite is pretty comprehensive from what I can see.

**Comment by unphased** [comment]
So I follow the readme instructions with cmake, but I get `No tests were found!!!`

Any tips?

Linux here

**Comment by SRombauts** [comment]
Did you 'git submodule init' and 'git submodule update'?
This is required to get the' googletest' library.

**Comment by unphased** [comment]
Yes (Also that should be somewhere in the readme)

**Comment by SRombauts** [comment]
Thanks for reporting, I'll open an issue about documentation.
