### ISSUE TITLE
Reading the database header

### ISSUE THREAD

**Issue by IRETD** [SRombauts/SQLiteCpp#210]
Why are there no functions for working with the database header?
For instance, it could be useful to get the total number of free list pages (offset 36) to calculate the actual database size before deciding whether to vacuum.

**Comment by patrick--** [comment]
@SRombauts I was thinking of tackling this - but wanted your thoughts on implementation.  What do you think of creating a structure to contain the header fields and then having a getHeaderInfo() function within the Database class that returns that struct?

**Comment by SRombauts** [comment]
Hello, I don't have a knowledge of the database header. How do you access it? 
What you propose seems reasonable

**Comment by patrick--** [comment]
Exactly! It's very similar to how you check if the database file is encrypted or not - except we would be parsing the entire header range for all of the different fields. 

Here is a version I did in C: https://github.com/patrick--/sqlite_header_parse 

I'll put an implementation / some tests together and submit a PR for your review and we can discuss further. 

Thanks!

**Comment by patrick--** [comment]
@SRombauts would you like me to add getHeaderInfo() usage in the `main.cpp` example file?

**Comment by SRombauts** [comment]
Hello, yes why not, to end the year well :)

**Comment by SRombauts** [comment]
Closing this since it has been implemented by @patrick-- in #249 Added SQLite header parsing functionality and associated tests
