### ISSUE TITLE
SQLiteCpp/build/libSQLiteCpp.so: undefined reference to `sqlite3_expanded_sql'

### ISSUE THREAD

**Issue by andrewdurkiewicz** [SRombauts/SQLiteCpp#213]
I am receiving only one sqlite3 undefined reference error after adding the -lsqlite3 flag. But this single error has been preventing g++ from building.

**Comment by SRombauts** [comment]
Hi, can you give me any more details, with some logs?

**Comment by mlin** [comment]
`sqlite3_expanded_sql()` was added in [SQLite 3.14 (2016-08-08)](https://sqlite.org/changes.html). Its unconditional use in Statement::getExpandedSQL() seems inconsistent with [README.md's statement of compatibility](https://github.com/SRombauts/SQLiteCpp#dependencies) back to 3.7.15. I guess it'd be nice to have a switch to opt-out of that member function.
