### ISSUE TITLE
Exception near syntax error

### ISSUE THREAD

**Issue by mickes27** [SRombauts/SQLiteCpp#214]
`namespace constants {
	const std::string select_external_key_query = "SELECT name FROM ? WHERE ID = ?";
}
`

Creating unique_ptr to SQL::Statement with this string as query throws "exception near ? syntax error". When deleting first ? (coresponding to table) everything works fine

**Comment by SRombauts** [comment]
Hi,

The issue is that you cannot use parameters for table name, only for values

Cheers
