### ISSUE TITLE
CMP0048 Policy warnings, because no version is being set with project(...)

### ISSUE THREAD

**Issue by jxsl13** [SRombauts/SQLiteCpp#216]
Exactly the same problem as this here:
https://github.com/cpp-redis/cpp_redis/issues/47

**Comment by SRombauts** [comment]
Thank you for reporting this issue.

**Comment by jxsl13** [comment]
it is also possible to get the version number from some source file like this project does: https://github.com/teeworlds/teeworlds/blob/master/CMakeLists.txt
