### ISSUE TITLE
Update sqlite to 3.29.0

### ISSUE THREAD

**Issue by prsolucoes** [SRombauts/SQLiteCpp#217]
Hi,

Can you update sqlite to 3.29.0?

There is a new version with the sqlite3 update? If yes, answer here when it is updated to we update the conan repository.

Thanks.

**Comment by SRombauts** [comment]
Thanks, I update to sqlite 3.29.0 and will mark the result as a new release of SQLiteCpp 2.4.0

**Comment by SRombauts** [comment]
https://github.com/SRombauts/SQLiteCpp/releases/tag/2.4.0 :)
