### ISSUE TITLE
clang-tidy complains on SQLite::OPEN_READWRITE | SQLite::OPEN_CREATE

### ISSUE THREAD

**Issue by saadlu** [SRombauts/SQLiteCpp#223]
C++ newbie question really,

so clang-tidy complains on 

Database db("blah.db", SQLite::OPEN_READWRITE | SQLite::OPEN_CREATE)

saying "Use of a signed integer operand with a binary bitwise operator". which seems to be case since both the constants are signed int and we are using the bitwise OR operator on them.

they are externally defined but from the code I see they are defined to

SQLITE_OPEN_READWRITE
SQLITE_OPEN_CREATE

which, in turn is defined as

```
#define SQLITE_OPEN_READWRITE        0x00000002
#define SQLITE_OPEN_CREATE           0x00000004 
``` 
https://www.sqlite.org/c3ref/c_open_autoproxy.html

I can use `0x6` to make the warning go away, but should there be a more solution at this library level (more abstract)

**Comment by SRombauts** [comment]
Hello,

I was pretty sure I had already answer this one, sorry!
This seems to be more a problem with the diagnostic because what I am doing is actually proper use of C flags.

Cheers
Sébastien
