### ISSUE TITLE
Support for variadic arguments?

### ISSUE THREAD

**Issue by emmenlau** [SRombauts/SQLiteCpp#227]
I'm completely new to SQLiteCpp, so please forgive if I overlooked something.

I'm under the impression that SQLiteCpp requires an explicit call to `bind()` for each parameter, is that correct? It does not support variadic arguments for the parameters, does it?

I've seen other database libraries support variadic arguments in unprepared statements, and/or in the execution of prepared statements. I find this helps condense the code, and make it more readable.

Would it be possible to add this?

**Comment by emmenlau** [comment]
Answering my own request, I found header `SQLiteCpp/VariadicBind.h` that adds support for variadic arguments to `bind()`. Thanks!

**Comment by SRombauts** [comment]
Nice, sorry for not answering you myself earlier
