### ISSUE TITLE
How do I get the error num returned by sqlite, I need to handle the exception according to the error num

### ISSUE THREAD

**Issue by ASaltyFishBoy** [SRombauts/SQLiteCpp#238]
How do I get the error num returned by sqlite, I need to handle the exception according to the error num

**Comment by patrick--** [comment]
I think they should be accessible using `getErrorCode()` and `getExtendedErrorCode()`. 

An example of that usage can be found in the database test file [here](https://github.com/SRombauts/SQLiteCpp/blob/c1ab7075f4133a7a9178aa6b70660e0421bcabf7/tests/Database_test.cpp#L284)

**Comment by SRombauts** [comment]
Yes, that's true, thanks @patrick-- for answering!
