### ISSUE TITLE
Dealing with multiple inserts

### ISSUE THREAD

**Issue by saaqibz** [SRombauts/SQLiteCpp#24]
Hello, Is there a command like executemany() for dealing with multiple inserts?

**Comment by SRombauts** [comment]
For future reference, [link to the python documentation](https://docs.python.org/2/library/sqlite3.html):

```python
# Larger example that inserts many records at a time
purchases = [('2006-03-28', 'BUY', 'IBM', 1000, 45.00),
             ('2006-04-05', 'BUY', 'MSFT', 1000, 72.00),
             ('2006-04-06', 'SELL', 'IBM', 500, 53.00),
            ]
c.executemany('INSERT INTO stocks VALUES (?,?,?,?,?)', purchases)
```

**Comment by xsacha** [comment]
If you were to make this function, would it be useful to have a bool option to start transaction and end transaction around the execution?
Right now I have a function myself that does this once per second.

**Comment by SRombauts** [comment]
Hi @xsacha, I am not sure of what you mean, can you give a simple example?

**Comment by xsacha** [comment]
I just mean to have:

db->exec("BEGIN");
query->reset();
for (auto statement: collection)
{
    // bind everything in statement
    query->bind(..);
}
db->exec("END");

**Comment by SRombauts** [comment]
This as finally been implemented and integrated, thanks to @maxbachmann!
