### ISSUE TITLE
Is a single SQLite::Database object safe to be used by multiple threads, when it's read-only?

### ISSUE THREAD

**Issue by Deanseo** [SRombauts/SQLiteCpp#246]
In the README page it's stated that:

> Thus, SQLiteC++ naturally supports the "Multi Thread" mode of SQLite: "In this mode, SQLite can be safely used by multiple threads provided that **no single database connection is used simultaneously in two or more threads**."

Supposed that `SQLite::Database` represents the _connection_, what if I can guarantee that it's going to be _always_ read-only? (say, by only using `SELECT` clauses)

Will that make it thread-safe to use a single `SQLite::Database` object touched by multiple threads?

**Comment by SRombauts** [comment]
Hello,
SQLiteCpp would be fine with it, but sqlite3 itself will only work with a multithreaded shared connection if you enforce the "serialized" thread safe (most expansive) mode

Cheers!

**Comment by Deanseo** [comment]
@SRombauts Thanks! Happy new year!

**Comment by SRombauts** [comment]
Happ new year,
