### ISSUE TITLE
When specifying an out-of-tree source a binary directory must be explicitly specified.

### ISSUE THREAD

**Issue by poldi171254** [SRombauts/SQLiteCpp#250]
Hi,
Trying to follow the Linux example of including the wrapper in another cmake project and am getting the following error.

/home/llist/kdedev/src/amarok/CMakeLists.txt:335: error: add_subdirectory not given a binary directory but the given source directory "/home/llist/kdedev/src/SQLiteCpp" is not a subdirectory of "/home/llist/kdedev/src/amarok".  When specifying an out-of-tree source a binary directory must be explicitly specified.

The main project is ins .../src/amarok and SqliteCpp is in .....src/SqliteCpp
Not sure what I'm missing
Thanks

**Comment by SRombauts** [comment]
Hello, please have a look at https://stackoverflow.com/a/15570165, but in short:

If add_subdirectory is not using a subdirectory, you have to explicitly specify a binary directory for it as well. Example:

add_subdirectory(/home/llist/kdedev/src/SQLiteCpp SQLiteCpp)
The second argument given as a relative path is interpreted relative to CMAKE_CURRENT_BINARY_DIR.

Let me know how it goes, 
Sébastien

**Comment by poldi171254** [comment]
Thanks for the quick reply. Have specified the bin directory and am getting much further.
I;m trying to use Ubuntu's sqlite-dev package so I have switch off the the internal sqlite. 

Seems to compile ok, but am getting these linking errors

`[100%] Built target amarokcollectionscanner
Scanning dependencies of target SQLiteCpp_autogen
[100%] Automatic MOC for target SQLiteCpp
[100%] Built target SQLiteCpp_autogen
Scanning dependencies of target SQLiteCpp
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Column.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Database.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Exception.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Statement.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Transaction.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/SQLiteCpp_autogen/mocs_compilation.cpp.o                                                                                               
[100%] Linking CXX shared library /home/llist/kdedev/build/amarok/bin/libSQLiteCpp.so
/usr/bin/ld: CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o: in function `SQLite::Backup::Backup(SQLite::Database&, char const*, SQLite::Database&, char const*)':
/home/llist/kdedev/src/SQLiteCpp/src/Backup.cpp:28: undefined reference to `sqlite3_backup_init'
/usr/bin/ld: CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o: in function `SQLite::Backup::Backup(SQLite::Database&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, SQLite::Database&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/llist/kdedev/src/SQLiteCpp/src/Backup.cpp:46: undefined reference to `sqlite3_backup_init'
/usr/bin/ld: CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o: in function `SQLite::Backup::Backup(SQLite::Database&, SQLite::Database&)':
/home/llist/kdedev/src/SQLiteCpp/src/Backup.cpp:61: undefined reference to `sqlite3_backup_init'
/usr/bin/ld: CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o: in function `SQLite::Backup::~Backup()':
/home/llist/kdedev/src/SQLiteCpp/src/Backup.cpp:77: undefined reference to `sqlite3_backup_finish'
/usr/bin/ld: CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o: in function `SQLite::Backup::executeStep(int)':
`
Thanks,
Leo

**Comment by poldi171254** [comment]
Thanks for the quick reply. Have specified the bin directory and am getting much further.
I;m trying to use Ubuntu's sqlite-dev package so I have switch off the the internal sqlite. 

Seems to compile ok, but am getting these linking errors

`[100%] Built target amarokcollectionscanner
Scanning dependencies of target SQLiteCpp_autogen
[100%] Automatic MOC for target SQLiteCpp
[100%] Built target SQLiteCpp_autogen
Scanning dependencies of target SQLiteCpp
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Column.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Database.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Exception.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Statement.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Transaction.cpp.o
[100%] Building CXX object /home/llist/kdedev/bin/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/SQLiteCpp_autogen/mocs_compilation.cpp.o                                                                                               
[100%] Linking CXX shared library /home/llist/kdedev/build/amarok/bin/libSQLiteCpp.so
/usr/bin/ld: CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o: in function `SQLite::Backup::Backup(SQLite::Database&, char const*, SQLite::Database&, char const*)':
/home/llist/kdedev/src/SQLiteCpp/src/Backup.cpp:28: undefined reference to `sqlite3_backup_init'
/usr/bin/ld: CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o: in function `SQLite::Backup::Backup(SQLite::Database&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, SQLite::Database&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/llist/kdedev/src/SQLiteCpp/src/Backup.cpp:46: undefined reference to `sqlite3_backup_init'
/usr/bin/ld: CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o: in function `SQLite::Backup::Backup(SQLite::Database&, SQLite::Database&)':
/home/llist/kdedev/src/SQLiteCpp/src/Backup.cpp:61: undefined reference to `sqlite3_backup_init'
/usr/bin/ld: CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o: in function `SQLite::Backup::~Backup()':
/home/llist/kdedev/src/SQLiteCpp/src/Backup.cpp:77: undefined reference to `sqlite3_backup_finish'
/usr/bin/ld: CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o: in function `SQLite::Backup::executeStep(int)':
`

**Comment by poldi171254** [comment]
Sorry, but just realized that I gave no info of my setup.

From your original example I now only have two lines
`        find_path(WRAPPEROK
            "CMakeLists.txt"
            "../SQLiteCpp")
        if(WRAPPEROK)
            add_subdirectory(/home/llist/kdedev/src/SQLiteCpp /home/llist/kdedev/bin/SQLiteCpp)
            include_directories(/home/llist/kdedev/include/SQLiteCpp)
        else()
            message(STATUS "You need to clone the wrapper first")
        endif()`

The statement 

> add_executable(main src/main.cpp)
caused my main program (amarok) to fail

The statement

> target_link_libraries
Gave errors about the link libraries being outside the tree

**Comment by SRombauts** [comment]
It seems to me that it is simply not linking with libsqlite3-dev... 

In this case, I think you might have hit a bug in SQLiteCpp: can you update to latest version?

Can you post the logs of CMake generating your Makefile please?

**Comment by poldi171254** [comment]
Don't know much about CMake, but tried the following changes with the latest SQLiteCpp code and CMake now builds SQLiteCpp with the following command
`cmake -DCMAKE_INSTALL_PREFIX=$HOME/kdedev -DCMAKE_BUILD_TYPE=Debug -j4 -DCMAKE_VERBOSE_MAKEFILE=TRUE -DSQLITECPP_INTERNAL_SQLITE=OFF /home/llist/kdedev/src/SQLiteCpp/`

My application I'm trying to incorprate SQLiteCpp with now also builds without errors

The git diff is
`llist@llist-VirtualBox-2:~/kdedev/src/SQLiteCpp$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 32e2a96..a783c26 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -43,7 +43,7 @@ else (MSVC)
     set(CPPLINT_ARG_OUTPUT      "--output=eclipse")
     set(CPPCHECK_ARG_TEMPLATE   "--template=gcc")
     # Useful compile flags and extra warnings
-    add_compile_options(-fstack-protector -Wall -Wextra -Wpedantic -Wno-long-long -Wswitch-enum -Wshadow -Winline)
+    add_compile_options(-fstack-protector -Wall -Wextra -Wpedantic -Wno-long-long -Wswitch-enum -Wshadow -Winline -fexceptions)
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-c++0x-compat") # C++ only
     if (CMAKE_COMPILER_IS_GNUCXX)
         # GCC flags
@@ -246,11 +246,8 @@ if (SQLITECPP_INTERNAL_SQLITE)
     target_include_directories(sqlite3 PUBLIC "${PROJECT_SOURCE_DIR}/sqlite3")
     target_include_directories(SQLiteCpp PRIVATE "${PROJECT_SOURCE_DIR}/sqlite3")
 else (SQLITECPP_INTERNAL_SQLITE)
-    find_package (SQLite3 REQUIRED)
-    if (SQLITE3_FOUND)
         include_directories(${SQLITE3_INCLUDE_DIRS})
-        target_link_libraries (SQLiteCpp ${SQLITE3_LIBRARIES})
-    endif (SQLITE3_FOUND)
+        target_link_libraries (SQLiteCpp sqlite3)
 endif (SQLITECPP_INTERNAL_SQLITE)
 
 # Optional additional targets:
diff --git a/googletest b/googletest
index 703bd9c..ec44c6c 160000
--- a/googletest
+++ b/googletest
@@ -1 +1 @@
-Subproject commit 703bd9caab50b139428cea1aaff9974ebee5742e
+Subproject commit ec44c6c1675c25b9827aacd08c02433cccde7780
`

**Comment by SRombauts** [comment]
Thanks

**Comment by poldi171254** [comment]
I there anything you want me to do with the change?
