### ISSUE TITLE
undefined reference to `SQLite::Database::Deleter::operator()(sqlite3*)'

### ISSUE THREAD

**Issue by poldi171254** [SRombauts/SQLiteCpp#266]
I've now used SQLiteCpp for the last few week in the project I'm working on (Amarok) without any issues.
After getting the latest version of SQLiteCpp I'm getting the following error

`/usr/bin/ld: CMakeFiles/amarok_storage-sqlitestorage.dir/SQLiteStorage.cpp.o: in function `std::unique_ptr<sqlite3, SQLite::Database::Deleter>::~unique_ptr()':
/usr/include/c++/8/bits/unique_ptr.h:274: undefined reference to `SQLite::Database::Deleter::operator()(sqlite3*)'
collect2: error: ld returned 1 exit status`

I'm guessing that this error is related to the later release as I'm working on a VM and if I restore the snapshot with working code and get the latest version of SQLiteCpp, I get the above error.
Thanks,
Leo

**Comment by SRombauts** [comment]
Hello, would you be able to give me more information on your setup please?
OS, compiler, perhaps some flags you use to compile & link.

The error you see is clearly about some recent changes on master on converting code to C++11.
This is quite tested on a few variants for Ubuntu distros & compilers (not yet release though) but probably not enough to cover your use case I guess.

I'll have a look to see if I can think of something

**Comment by SRombauts** [comment]
I think you might simply be missing the compilation of
Database.cpp line 74:
`// Deleter functor to use with smart pointers to close the SQLite database connection in an RAII fashion.
void Database::Deleter::operator()(sqlite3* apSQLite)
`

**Comment by poldi171254** [comment]
Sorry,
The system info is
Operating System: Kubuntu 19.04
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.2
Kernel Version: 5.0.0-38-generic
OS Type: 64-bit
Processors: 6 × AMD Phenom(tm) II X6 1100T Processor
Memory: 7.8 GiB of RAM

I've attached the output from cmake and cmake --build
Thanks,
Leo
[cmakeAndBuild.txt](https://github.com/SRombauts/SQLiteCpp/files/4125441/cmakeAndBuild.txt)

**Comment by SRombauts** [comment]
Hello, sorry but I cannot see anything wrong in your log here... no "error"

**Comment by poldi171254** [comment]
True. The errors only show when I compile the  Amarok code that uses SQLiteCpp. I've attache a file that shows the output for the compilation for a class. The first part shows the build without any errors (previous version of SQLiteCpp). The second part show the build with the latest version of SQLiteCpp. 

The Amarok code did not change between the two compiles

Leo
[CompilesDiffs.txt](https://github.com/SRombauts/SQLiteCpp/files/4137423/CompilesDiffs.txt)

**Comment by SRombauts** [comment]
This is a bit worrying; how are you linking to the SQLiteCpp library? dyn / statically? 

To me it looks a bit like if you would be actually still be linking with an older copy the of library.

**Comment by poldi171254** [comment]
I think the issue is at my end. I'm investigating and will let you know what I find

**Comment by poldi171254** [comment]
I have rebuilt SQLiteCpp with the internal SQLite3 source and everything works.

**Comment by SRombauts** [comment]
Thanks, all is good then 😊
