### ISSUE TITLE
'SQLiteCpp/SQLiteCpp.h' file not found

### ISSUE THREAD

**Issue by bear24rw** [SRombauts/SQLiteCpp#267]
Master branch seems to have broken header file exporting:

```
git clone --recursive https://github.com/SRombauts/SQLiteCpp_Example.git
cd SQLiteCpp_Example/SQLiteCpp
git checkout master
cd ..
mkdir build
cd build
cmake ..
make
/tmp/SQLiteCpp_Example/src/main.cpp:17:10: fatal error: 'SQLiteCpp/SQLiteCpp.h' file not found
#include <SQLiteCpp/SQLiteCpp.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

It works correctly with the tagged version in the example project: SQLiteCpp @ 8485bb7

**Comment by SRombauts** [comment]
Hello,
can you please give a bit of context? 
All CI builds are green so I suspect that it is something specific to your OS, compiler, or perhaps CMake version.

**Comment by SRombauts** [comment]
Ok, I get it, let me try the example

**Comment by SRombauts** [comment]
Thanks for reporting @bear24rw!

Looking at recent changes, it's easy to see that it's coming from
91fe2d75 Merge pull request #234 support for external sqlite3 from BioDataAnalysis/emmenlau_support_external_sqlite

@emmenlau any inputs on this?

Then, I should find a way to test all this with a Github Action CI in this repository, so we would keep track this on all pull requests!

**Comment by bear24rw** [comment]
Thanks for the fast fix!

**Comment by emmenlau** [comment]
I think the fix may introduce a code duplication in cmake: https://github.com/SRombauts/SQLiteCpp/commit/76bd3b2f543453e093bfffa20ea4de75dc169966#commitcomment-37028296
An idea for a simpler solution is also given in the comment. Let me know if I should make a PR for this tomorrow?

**Comment by SRombauts** [comment]
Sorry, I was too tired, but I have fixed my fix thanks to your feedback :)

**Comment by emmenlau** [comment]
Awesome, thanks for your always quick support @SRombauts ! Let me know if there are sometimes cmake questions, I may find a bit of time to help...

**Comment by SRombauts** [comment]
Ah, sadly not always quick, I have a newborn baby at home!

Right now I think that the project is nearly in a good shape for a first 3.0 release: my only one question is about the cxx standard flag.
We need to express a minimum version, not a specific required version 
There is already a PR on this, would you please have a look at it?

**Comment by emmenlau** [comment]
I guess its the https://github.com/SRombauts/SQLiteCpp/pull/239 about c++20?

**Comment by emmenlau** [comment]
Here is a proposal: https://github.com/SRombauts/SQLiteCpp/pull/269. In my humble opinion, this new PR adds the best of all worlds. It does not need a lot of extra logic, but allows users to specify any c++ standard. It still enforces the bare minimum requirement (c++11 if tests are enabled).

What do you think?
