### ISSUE TITLE
SQLite cannot get column  no such module: FTS5

### ISSUE THREAD

**Issue by poldi171254** [SRombauts/SQLiteCpp#270]
Trying to match mysql FULLTEXT Index feature and found a reference to FTS5.

The query 
CREATE VIRTUAL TABLE podcastchannels using FTS5 (id INTEGER,url TEXT,title TEXT,weblink TEXT,image TEXT,description TEXT,copyright VARCHAR(255),directory VARCHAR(255),labels VARCHAR(255),subscribedate VARCHAR(255),autoscan BOOL, fetchtype INTEGER,haspurge BOOL, purgecount INTEGER,writetags BOOL, filenamelayout VARCHAR(1024) );" 

throws the following error
SQLite cannot get column  no such module: FTS5

Thanks
Leo

**Comment by kcowolf** [comment]
In case you're still seeing this, make sure you define the SQLITE_ENABLE_FTS5 flag when you build SQLite/SQLiteCpp.  I used FTS with SQLiteCpp for a bit and it worked fine.
