### ISSUE TITLE
Supporting WSL by enabling optional default Database constructors

### ISSUE THREAD

**Issue by Naville** [SRombauts/SQLiteCpp#272]
I currently uses the following CMake:
```
# Detecting WSL
IF(EXISTS "/proc/version")
  file(READ "/proc/version" PROC_VERSION)
  string(FIND "${PROC_VERSION}" "Microsoft" PROC_VERSION_IS_MS)
  if(NOT "${PROC_VERSION_IS_MS}" MATCHES "-1")
      message("WSL Detected. Using workaround for broken fcntl")
      add_compile_definitions("USING_WSL")
  endif()
ENDIF()
```
and 

```
#ifdef USING_WSL
  Database DB(DBPath,SQLite::OPEN_READWRITE | OPEN_CREATE,"unix-dotfile");
#else
  Database DB(DBPath, SQLite::OPEN_READWRITE | OPEN_CREATE);
#endif
```

To workaround the lack of ``fcntl`` support on Windows WSL. I figured if this could be tested and probably merged into the main project

**Comment by SRombauts** [comment]
Hi, can you tell le what is not working correctly une Windows Subsystem for Linux ?
I was under thé impression that is was working correctly, with all unit tests passing. 

What change to the Database constructor are you proposing?

Cheers !

**Comment by Naville** [comment]
@SRombauts See https://github.com/microsoft/WSL/issues/2395 and its comments, better than my own words

**Comment by Naville** [comment]
> What change to the Database constructor are you proposing?
I was hoping that the ``aVfs`` argument here defaults to ``"unix-dotfile"`` on WSL so library users dont have to explicitly deal with this https://github.com/SRombauts/SQLiteCpp/blob/be1a8eeace02ce98dfa3da688d1011c5bb895985/include/SQLiteCpp/Database.h#L146

**Comment by SRombauts** [comment]
Ah yes, I see !
Let me see how to reproduce the issue first
