### ISSUE TITLE
CMAKE_BUILD_TYPE not used on windows

### ISSUE THREAD

**Issue by SylvainCorlay** [SRombauts/SQLiteCpp#279]
It appears that the `CMAKE_BUILD_TYPE`  standard cmake flag is ignored.

What is the appropriate way to produce a release build of SQLiteCpp on windows?

**Comment by sum01** [comment]
Windows is a multi-config build system, so you can do the following (assuming you're currently cd'd to the repo).
```cmake
mkdir build
cd build
cmake ..
cmake --build . --config Release
```

This'll be the same for all projects you might build with Cmake.

**Comment by SRombauts** [comment]
Yes, thanks for answering.

It's done like that in CI https://github.com/SRombauts/SQLiteCpp/blob/master/appveyor.yml and https://github.com/SRombauts/SQLiteCpp/blob/master/.github/workflows/build.yml
