### ISSUE TITLE
Missing SQLITE_OPEN_FULLMUTEX flag in SQLite namespace

### ISSUE THREAD

**Issue by rwrx** [SRombauts/SQLiteCpp#282]
Would you also want to add a SQLITE_OPEN_FULLMUTEX into SQLite namespace?

**Comment by SRombauts** [comment]
Yes, you are right we should

**Comment by rwrx** [comment]
Ok, I can create a pull request if you would want.

**Comment by SRombauts** [comment]
Yes please 😀

**Comment by rwrx** [comment]
I have created a pull request here: https://github.com/SRombauts/SQLiteCpp/pull/284
