### ISSUE TITLE
Does this library support the JSON1 extension?

### ISSUE THREAD

**Issue by remz1337** [SRombauts/SQLiteCpp#289]
Hello,

I would like to use this library to store JSON objects in sqlite. Does this library support the JSON1 extension?

Thanks

**Comment by SRombauts** [comment]
Hi, thanks for asking, apparently someone else just proposed that: #289

**Comment by SRombauts** [comment]
Sorry, I fixed the reference (had to search for json1) it's #288 allow building of SQLite JSON1 extension when building internal sqlite library
