### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by rwrx** [SRombauts/SQLiteCpp#290]
Hello, I just have question on when do you plan to release a new version?

**Comment by SRombauts** [comment]
Hello, do you want a release quickly?

I have currently no plan for one: I could do one shortly but usually, I spend some time reviewing pull requests & bugs before (which I don't have currently).
Do you see anything of particular interest for you?

Cheers!
Sébastien

**Comment by rwrx** [comment]
No, I do not want to release quickly. I just wanted to integrate this change https://github.com/SRombauts/SQLiteCpp/pull/284 into my repository and use tagged version, not specific commit or latest master. But only if this minor release (maybe 3.0.1) makes sense for you.

**Comment by SRombauts** [comment]
3.1.0 it is, since there are a couple of new API:
https://github.com/SRombauts/SQLiteCpp/releases/tag/3.1.0

Enjoy, and thanks for your support 👍 
Sébastien
