### ISSUE TITLE
Accept std::filesystem::path in Database constructor

### ISSUE THREAD

**Issue by Chronial** [SRombauts/SQLiteCpp#296]
It would be helpful if SQLiteCpp would accept a `std::filesystem::path` as the database path.

That would shift some work from the users of the library to the library, since sqlitecpp would then have to take care of converting the path to utf8.

**Comment by sum01** [comment]
That would require a minimum of C++17. I'm all for moving forward, but I would guess some might have a problem with that.

As an aside, it's worth pointing out that `std::filesystem::path` has a `u8string()` method, so there's no extra work to convert to u8.

**Comment by SRombauts** [comment]
Thanks for asking, and many thanks to @ptrks for providing an implementation a few days ago
