### ISSUE TITLE
Makefile errors

### ISSUE THREAD

**Issue by Aykelith** [SRombauts/SQLiteCpp#3]
When I make the Makefile generated by cmake I get those errors:

Scanning dependencies of target SQLiteCpp
[ 20%] Building CXX object src/CMakeFiles/SQLiteCpp.dir/Column.cpp.o
[ 40%] Building CXX object src/CMakeFiles/SQLiteCpp.dir/Database.cpp.o
[ 60%] Building CXX object src/CMakeFiles/SQLiteCpp.dir/Statement.cpp.o
/home/alexxanderx/Work/Programare/Libraries/SQLiteCpp-master/src/Statement.cpp: In member function ‘void SQLite::Statement::bind(int, const string&)’:
/home/alexxanderx/Work/Programare/Libraries/SQLiteCpp-master/src/Statement.cpp:69:79: warning: conversion to ‘int’ from ‘std::basic_string<char>::size_type {aka long unsigned int}’ may alter its value [-Wconversion]
/home/alexxanderx/Work/Programare/Libraries/SQLiteCpp-master/src/Statement.cpp: In member function ‘void SQLite::Statement::bind(const char_, const string&)’:
/home/alexxanderx/Work/Programare/Libraries/SQLiteCpp-master/src/Statement.cpp:123:80: warning: conversion to ‘int’ from ‘std::basic_string<char>::size_type {aka long unsigned int}’ may alter its value [-Wconversion]
/home/alexxanderx/Work/Programare/Libraries/SQLiteCpp-master/src/Statement.cpp: In constructor ‘SQLite::Statement::Ptr::Ptr(sqlite3_, std::string&)’:
/home/alexxanderx/Work/Programare/Libraries/SQLiteCpp-master/src/Statement.cpp:272:72: warning: conversion to ‘int’ from ‘std::basic_string<char>::size_type {aka long unsigned int}’ may alter its value [-Wconversion]
[ 80%] Building CXX object src/CMakeFiles/SQLiteCpp.dir/Transaction.cpp.o
Linking CXX static library libSQLiteCpp.a
[ 80%] Built target SQLiteCpp
Scanning dependencies of target example1
[100%] Building CXX object CMakeFiles/example1.dir/examples/example1/main.cpp.o
/home/alexxanderx/Work/Programare/Libraries/SQLiteCpp-master/examples/example1/main.cpp: In function ‘int main()’:
/home/alexxanderx/Work/Programare/Libraries/SQLiteCpp-master/examples/example1/main.cpp:302:37: warning: conversion to ‘int’ from ‘size_t {aka long unsigned int}’ may alter its value [-Wconversion]
Linking CXX executable example1
src/libSQLiteCpp.a(Column.cpp.o): In function `SQLite::Column::getName() const':
Column.cpp:(.text+0x163): undefined reference to`sqlite3_column_origin_name'
collect2: error: ld returned 1 exit status
make[2]: **\* [example1] Error 1
make[1]: **\* [CMakeFiles/example1.dir/all] Error 2
make: **\* [all] Error 2

**Comment by bidasknakayama** [comment]
I still have this problem.

I am using sqlite3.a ( I build by myself )...

**Comment by bidasknakayama** [comment]
sorry, I read this .
and I could build with the flag !
http://source.online.free.fr/Linux_HowToCompileSQLite.html
thank you. I will enjoy code : )
