### ISSUE TITLE
Using SQLiteCpp with SQLCipher

### ISSUE THREAD

**Issue by waqqasjabbar** [SRombauts/SQLiteCpp#303]
Hi,
I would like to use SQLiteCpp with SQLCipher. SQLCipher provide all the APIs of SQLite3 with additional functionality of encryption (using PRAGMA key = "<key>"). It seems like SQLiteCpp is dependant on SQLite3. Is there a way to link SQLiteCpp with SQLCipher instead of SQLite3?

Thanks
waqqas

**Comment by paulo-coutinho** [comment]
Nice question. Any solution for this?

**Comment by waqqas** [comment]
@paulo-coutinho I wrote my own header-only c++ wrapper that should work with both sqlcipher and sqlite3.  Check it out at [here](https://github.com/waqqas/sqliter)

**Comment by linux-fan-dave** [comment]
This is already fixed - see the CMakeLists.txt

**Comment by 89trillion-feiyang** [comment]
Any news about this?

**Comment by paulocoutinhox** [comment]
Hi @89trillion-feiyang,

You can set cmake option "SQLITE_HAS_CODEC" to "ON".

It will require that your cipher library implement `sqlite3_key` and `sqlite3_key_v2` methods, like this:
https://github.com/sqlcipher/sqlcipher/search?q=sqlite3_key%20sqlite3_key_v2

If you enable it, cmake project will try import sqlcipher:
https://github.com/SRombauts/SQLiteCpp/blob/master/CMakeLists.txt#L251-L285

Maybe it solve your problem.

**Comment by 89trillion-feiyang** [comment]
> 

Thank you very much! I solved my problem, thanks again.

**Comment by 89trillion-feiyang** [comment]
> Hi @89trillion-feiyang,
> 
> You can set cmake option "SQLITE_HAS_CODEC" to "ON".
> 
> It will require that your cipher library implement `sqlite3_key` and `sqlite3_key_v2` methods, like this: https://github.com/sqlcipher/sqlcipher/search?q=sqlite3_key%20sqlite3_key_v2
> 
> If you enable it, cmake project will try import sqlcipher: https://github.com/SRombauts/SQLiteCpp/blob/master/CMakeLists.txt#L251-L285
> 
> Maybe it solve your problem.


Thank you.
According to your solution, I solved my problem, thanks again
