### ISSUE TITLE
[BUG] filesystem: No such file or directory

### ISSUE THREAD

**Issue by 0NG** [SRombauts/SQLiteCpp#322]
Bug may exist in [this line](https://github.com/SRombauts/SQLiteCpp/blob/master/include/SQLiteCpp/Database.h#L17).

I use SQLiteCpp on WSL (Ubuntu 18.04 and Ubuntu 20.04) and compile it with `--std=c++17`. However, it always raises an error `filesystem: No such file or directory`. 

After debugging, I found that `__cplusplus = 201703`, so `(__cplusplus >= 201703L) && ((!defined(__MINGW32__) && !defined(__MINGW64__)) || (__GNUC__ > 8))` must be `true`. But, my g++ version is 7.5 and I know from [this answer](https://stackoverflow.com/a/45867491) that 'GCC v7 still does not implement \<filesystem\>'.

Maybe this is a bug? I haven't test it on a real Linux system.

**Comment by guoh27** [comment]
+1

**Comment by SplitGemini** [comment]
gcc 7.5 not has std::filesystem but std::experimental::filesystem  
see [nlohmann/json/pull/3101](https://github.com/nlohmann/json/pull/3101) and [nlohmann/json/issues/3090](https://github.com/nlohmann/json/issues/3090), please fix

**Comment by paulo-coutinho** [comment]
+1

**Comment by SRombauts** [comment]
Fixed quite some time ago by the second PR
