### ISSUE TITLE
[Question] Possible to bind NULL ?

### ISSUE THREAD

**Issue by omar-a-007** [SRombauts/SQLiteCpp#323]
_For example_
```
SQLite::Statement query(db, "INSERT INTO media VALUES (NULL, :CategoryID, :title)");
query.bind(":CategoryID", CategoryID); 
query.bind(":title", title); 
```

Where CategoryID is a Foreign Key works great unless I need to pass a null CategoryID, in which case an exception is thrown.
Doing a check and making CategoryID = "NULL" also doesn't work as that gets expanded to " 'NULL' "
Currently Im concatenating the variable within the insert statement itself as a workaround, but would like to find a more correct way with bind

**Comment by SRombauts** [comment]
Hello,
What is the exception beeing thrown? I expect it's in fact a question for the SQLite3 library itself.

**Comment by omar-a-007** [comment]
Well, in that example scenario, CategoryID is a foreign key, so it must be set to either NULL or an valid CategoryID. 
Setting it to a valid CategoryID works just fine, but if I want to pass in NULL, I have no way to do that.
For instance, I cant 
`query.bind(":CategoryID", NULL);  // this is a null ptr`
Similarly, I cant
`query.bind(":CategoryID", "NULL"); `

^ Produces the ExpandedSQL of `SQLite::Statement query(db, "INSERT INTO media VALUES (NULL, 'NULL', 'title')");`
NULL in this instance being a string type again throws a Constraint exception due to foreign key violation (and is undesired, as its the string 'NULL' as opposed to being a NULL value)

**Comment by omar-a-007** [comment]
here's a quick sample file, testme.cpp

```
#include <string>
#include <SQLiteCpp/SQLiteCpp.h>
int main ()
{
    try {
        SQLite::Database    db("testme.db3", SQLite::OPEN_READWRITE|SQLite::OPEN_CREATE); 
        db.exec("CREATE TABLE IF NOT EXISTS media (MID INTEGER PRIMARY KEY, CID INTEGER, FOREIGN KEY(CID) REFERENCES category(CID));");
		db.exec("CREATE TABLE IF NOT EXISTS category (CID INTEGER PRIMARY KEY, Title TEXT UNIQUE);");
        db.exec("PRAGMA foreign_keys = ON;"); 

        SQLite::Statement query(db, "INSERT INTO media VALUES (NULL, :CategoryID)");
        //query.bind(":CategoryID", 0);         // Generates FOREIGN KEY constraint failed, as it should
        //query.bind(":CategoryID", NULL);      // Unable to build: passing NULL to non-pointer argument
        query.bind(":CategoryID", "NULL");      // Generates FOREIGN KEY constraint failed, as it should


        std::cout << query.getExpandedSQL() << std::endl;       // couts: INSERT INTO media VALUES (NULL, 'NULL')
        std::cout << query.exec() << std::endl;
        remove("testme.db3");
    }
    catch (std::exception& e) {
        std::cout << "SQLite exception: " << e.what() << std::endl;
        remove("testme.db3");
        exit(EXIT_FAILURE);
    }

    return 0;
}
```

**Comment by michaeldurland** [comment]
There appears to be a bind function that allows binding to NULL:

`void bind(const char* apName) // bind NULL value`

Would that suffice?

**Comment by SRombauts** [comment]
> void bind(const char* apName) // bind NULL value
Yes, that's it, eg in unit tests:
- https://github.com/SRombauts/SQLiteCpp/blob/b611b5cf2859b9d7b982920ac9b7e4dfae83e062/tests/Statement_test.cpp#L356
