### ISSUE TITLE
support latest sqlite3 for ```returning``` clause

### ISSUE THREAD

**Issue by etorth** [SRombauts/SQLiteCpp#330]
The latest sqlite3 supports ```returning-clause``` to return affected rows in ```delete``` and others.
It's useful and could you please support it?

The first version supports returning-clause is 3.36, released on June 20, 2021.
https://github.com/sqlite/sqlite/releases/tag/version-3.36.0

```sql
sqlite> select * from tbl_secureditemlist;
fld_dbid  fld_itemid  fld_seqid  fld_count  fld_duration  fld_extattrlist
--------  ----------  ---------  ---------  ------------  ---------------
2         687         9          1          1             
2         687         6          1          1             
2         692         9          1          1             
2         692         8          1          1             
2         692         1          1          1             
2         687         8          1          1             
2         687         10         1          1             
2         692         4          1          1             
2         692         3          1          1             
2         687         11         1          1             
2         692         7          1          1             
2         692         6          1          1             
2         687         13         1          1             
2         692         5          1          1             
2         687         12         1          1             
2         687         14         1          1             
2         687         15         1          1             
2         687         7          1          1             
2         666         5          1          1             
2         687         16         1          1             
sqlite> delete from tbl_secureditemlist where fld_dbid = 2 and fld_itemid = 687 and fld_seqid = 9 returning *;
fld_dbid  fld_itemid  fld_seqid  fld_count  fld_duration  fld_extattrlist
--------  ----------  ---------  ---------  ------------  ---------------
2         687         9          1          1             
```

**Comment by jagerman** [comment]
> The first version supports returning-clause is 3.36

It's not *quite* that new: it was added in 3.35 (released 12 March 2021).

**Comment by jagerman** [comment]
Also for the record: I've used SQLiteCpp linked to a compatible sqlite3 (rather than the embedded copy) and RETURNING queries work just fine.

**Comment by etorth** [comment]
that's true, I can alternatively link to the newer SQLite version.
I mean, can SQLiteCpp pack the latest sqlite3 and distribute then we don't need extra dependency?

**Comment by SRombauts** [comment]
An up-to-date version of SQLite was in fact already packed in the `master` branch of the project at the time of the question:
Commit 0da8c467 by Sébastien Rombauts, 10/06/2021 06:24 PM
> Updated SQLite3 from 3.34.0 to 3.36.0 (2021-06-18)

I realize that it has taken way too long to officially release this support officially, but it is now in the latest https://github.com/SRombauts/SQLiteCpp/releases/tag/3.2.0

Cheers!
