### ISSUE TITLE
Feature request: move-assignment operator for Statement

### ISSUE THREAD

**Issue by Fytch** [SRombauts/SQLiteCpp#347]
(See #190)

The explicitly deleted copy-assignment operator of `SQLite::Statement` stops the compiler from generating a move-assignment operator for this type. On a related note, having a default constructor would also be nice. Consider the following example that I would wish to be able to write:

```cpp
struct foo
{
	SQLite::Database db;
	SQLite::Statement st;

	foo()
		: db(path, SQLite::OPEN_READWRITE)
	{
		// do stuff with db
		st = SQLite::Statement("SQL CODE");
	}
};
```
Currently, I have to box all statements that I use in this way into `optional`s. Ugly!

**Comment by SRombauts** [comment]
Hello Fytch, thanks a lot for your good suggestion!

This should have been totally obvious to me when I switch to using C++11, but that wasn't long ago, and I have been busy with work & family.

Can you perhaps provide a Pull Request for it?
I should be able to get more time to work on this project this year, let's make it great again :)
