### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by paulocoutinhox** [SRombauts/SQLiteCpp#357]
Hi,

When we will have a new version?

The latest release is from 2020.

Thanks.

**Comment by SRombauts** [comment]
Hi, it's a good question!

I wanted to release a few months ago but I noticed how the current status of the code is incoherent regarding the int/long vs int32_t/int64_t. I am now trying to merge a few more changes and tackle this issue

**Comment by paulocoutinhox** [comment]
Hi @SRombauts,

Do you have any update about new versions?

Thanks.

**Comment by SRombauts** [comment]
Hello,

I am giving it another try right now! Last time I stopped waiting for some more cleanups.

Thanks for asking, and don't hesitate to ask multiple times if needed ;)

Cheers!

**Comment by SRombauts** [comment]
I have just released https://github.com/SRombauts/SQLiteCpp/releases/tag/3.2.0

Let me know if we need some quick patches

**Comment by paulocoutinhox** [comment]
Thanks. Im trying updating it from conan to use in my projects:
https://github.com/nativium/nativium-modules
