### ISSUE TITLE
Last error code cannot be accessed

### ISSUE THREAD

**Issue by hwiesmann** [SRombauts/SQLiteCpp#37]
I have seen that you can access now from SQLite::Statement the last status. Why isn't there a method in SQLite::Database to get the last status / error code (,either)? This is useful in case you want to detect the reason in case an exception is raised and the exception handler has no access to the statement.

BTW: There is a method to get the last error message but not the status.

**Comment by SRombauts** [comment]
Sorry for the very unusual delay, I was busy with my family and other projects!
I've looked into this and decided to clean up the Statement class. I will remove the mLastStatus that is not always correct, and add an errcode() method (both to Database and Statement classes)

**Comment by hwiesmann** [comment]
Hi Sébastien,

thanks for the fix!
Regards,
Hartwig
