### ISSUE TITLE
How to get type of the column(field) from the empty table

### ISSUE THREAD

**Issue by YuichiKamishiro** [SRombauts/SQLiteCpp#373]
Table is empty and i need to get type of the fields.

**Comment by dougnazar** [comment]
Couple options that I can see.

Use a SQL query that forces a row (like an outer join):
```sql
SELECT t.* FROM (SELECT 1) s LEFT JOIN <table> t
```

or drop to using the low level functions like `sqlite3_column_decltype()`. There are various caveats, check the SQLite documentation. Probably not an API that should be added to this library.
