### ISSUE TITLE
SAVEPOINT

### ISSUE THREAD

**Issue by saaqibz** [SRombauts/SQLiteCpp#39]
Hi Sebastien,

I ran into an issue where I'm trying to do asynchronous concurrency on my application to keep the UI thread available. However, this ends up causing issues where transactions become embedded.

I believe sqlite does not allow begin and commits to be embedded but it does allow a form of embedded transactions to be supported using SAVEPOINT and RELEASE.
https://www.sqlite.org/lang_savepoint.html

Does SQLiteCpp support this?

**Comment by SRombauts** [comment]
Hi, sorry for the delay, I tried to look at this functionality, but I will need some time to test it.

**Comment by SRombauts** [comment]
Implemented by #299
