### ISSUE TITLE
Why wouldn't this bind work?

### ISSUE THREAD

**Issue by undeadindustries** [SRombauts/SQLiteCpp#398]
I search through old bugs and couldn't find this. Hoping you can help.

```
std::string querystr = "SELECT * FROM games g WHERE g.Name LIKE ?% ORDER BY g.Name ASC;"
SQLite::Statement query(db, querystr);
query.bind(1,"Mario");
std::cout << query.getExpandedSQL();
```

(output)
`"SELECT * FROM games g WHERE g.Name LIKE ?% ORDER BY g.Name ASC;`

Even when I remove the %, it is still not binding. 

Everything else seems to be working perfect. When I don't use bind and I just put something directly into the querystr, it works great...

I'm using the latest pull of SQLiteCpp.

EDIT: #include <SQLiteCpp/VariadicBind.h> is in the code. I didn't forget that.

**Comment by dougnazar** [comment]
Aside from the extra `%`, which you said you tried without, it works fine here.

Are you ignoring errors? It'll throw an exception if you include the `%` in the SQL statement since it'll be unable to parse that as valid SQL.

```c++
#include <iostream>
#include <string>
#include <SQLiteCpp/SQLiteCpp.h>

int main() {
    SQLite::Database db("test.db", SQLite::OPEN_READWRITE | SQLite::OPEN_CREATE);
    db.exec("CREATE TABLE IF NOT EXISTS games (id INTEGER PRIMARY KEY, Name TEXT)");

    std::string querystr = "SELECT * FROM games g WHERE g.Name LIKE ? ORDER BY g.Name ASC;";
    SQLite::Statement query(db, querystr);
    query.bind(1, "Mario%");
    std::cout << query.getExpandedSQL() << std::endl;

    return 0;
}
```

```sql
SELECT * FROM games g WHERE g.Name LIKE 'Mario%' ORDER BY g.Name ASC;
```

**Comment by undeadindustries** [comment]
This can be closed. Sorry to waste your time.
But your response did help! The query I was actually using was really complex. 
I didn't realize SQLite::Statement query(db, querystr); checks the statement for errors. 
I figured that happened during execution. There was an error in my statement so the TRY/CATCH caught it before bind...

THANK YOU!
