### ISSUE TITLE
unresolved external symbol on windows

### ISSUE THREAD

**Issue by hesa2020** [SRombauts/SQLiteCpp#416]
I am trying to use this repository in a cmake project for linux and windows.

It compiles correctly on linux but on windows I am getting the 2 following errors:
LNK2001	unresolved external symbol "int const SQLite::OPEN_READWRITE" (?OPEN_READWRITE@SQLite@@3HB)
LNK2001	unresolved external symbol "int const SQLite::OPEN_CREATE" (?OPEN_CREATE@SQLite@@3HB)

In my CMakeLists I only target_link_libraries like this:
```
IF (WIN32)
        set(PTHREAD)
    ELSE()
        set(PTHREAD pthread dl)
    ENDIF()

target_link_libraries(${PROJECT_NAME}
    PRIVATE
        SQLiteCpp
        sqlite3
        ${PTHREAD}
)
```

Is it missing a sub library that prevent sqlite library from being loaded?

**Comment by SRombauts** [comment]
You can have a look at the example subdirectory project
It runs in CI/CD by Github Actions as a way to ensure that we keep the CMake working for typical use cases
https://github.com/SRombauts/SQLiteCpp/actions/runs/4980294933/jobs/8913016051
