### ISSUE TITLE
cpplint report wrong messages

### ISSUE THREAD

**Issue by hongnod** [SRombauts/SQLiteCpp#418]
When set SQLITECPP_RUN_CPPLINT ON.  Following messages will appear, swith line ending to "LF" or "CRLF", the error messages are still there. In fact, the output binary or lib works fine.
[9/13] cmd.exe /C "cd /D D:\build\sqlitecipher\SQLiteCpp2\.build && D:\msys64\ucrt64\bin\python.exe D:...pp2/include/SQLiteCpp/VariadicBind.h D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/ExecuteMany.h
D:/build/sqlitecipher/SQLiteCpp2/src/Backup.cpp:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/src/Column.cpp:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/src/Database.cpp:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/src/Exception.cpp:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/src/Savepoint.cpp:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/src/Statement.cpp:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/src/Transaction.cpp:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/SQLiteCpp.h:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/Assertion.h:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/Backup.h:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/Column.h:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/Database.h:112: note: Lines should be <= 120 characters long  [whitespace/line_length] [3]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/Database.h:113: note: Lines should be <= 120 characters long  [whitespace/line_length] [3]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/Database.h:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/Exception.h:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/Savepoint.h:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/Statement.h:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/Transaction.h:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/VariadicBind.h:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
D:/build/sqlitecipher/SQLiteCpp2/include/SQLiteCpp/ExecuteMany.h:0: error: One or more carriage-return \r (^M) (Windows endline) found; Use only UNIX endline \n  [whitespace/newline] [5]
cpplint: Total errors found: 20

**Comment by SRombauts** [comment]
It is not an error, cpplint Python script is configured to report in case of using CRLF end of line, which can happen on Windows if you use [Git config core.crlf auto](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) for instance

**Comment by dian-yu-luo** [comment]
I don't want config that as global,could I config that only in cmakelists,this is my config :
``` cmake
FetchContent_Declare(
  SQLiteCpp
  GIT_REPOSITORY https://github.com/SRombauts/SQLiteCpp.git
  GIT_TAG master
)

FetchContent_MakeAvailable(SQLiteCpp)
```
