### ISSUE TITLE
Warning in Database File

### ISSUE THREAD

**Issue by paulocoutinhox** [SRombauts/SQLiteCpp#421]
Hi,

Im receiving a lot of warnings in this line in version 3.2.1 on macOS Monterey and clang 14:

```
/Users/paulo/.conan/data/sqlitecpp/3.2.1/_/_/package/60a13861f8cff70e88b38b3bf4bde5ae86f2a566/include/SQLiteCpp/Database.h:41:26: warning: extra tokens at end of #ifndef directive [-Wextra-tokens]
    #ifndef __has_include(<experimental/filesystem>)
                         ^
                         //
2 warnings generated.
```

Thanks.

**Comment by ninjaoflight** [comment]
Hi, this was fixed in #393 feel free to grab from the latest source to remove that warning

**Comment by paulocoutinhox** [comment]
Hi,

Can you launch a new release to I add it to conan?

Thanks.

**Comment by ninjaoflight** [comment]
@SRombauts I think it should be a good idea to make a new release, they are mostly error fixed and the Dynamic compilation for windows

**Comment by SRombauts** [comment]
Hello, I totally agree!

In fact, I should have released something very soon after the last one in December since it came with new warnings etc
In any case, I'll work on it, you can expect to see some activity 

I'll keep this issue open until it's done!

**Comment by SRombauts** [comment]
https://github.com/SRombauts/SQLiteCpp/releases/tag/3.3.0 🎉 

Let me know how it works for you, and this time I plan to release a quick patch if we end up fixing a few things right after the release

Cheers!
Sébastien
