### ISSUE TITLE
SQLITE_ENABLE_JSON1 flag does not appear to compile sqlite3 with this option

### ISSUE THREAD

**Issue by jcurtis-cc** [SRombauts/SQLiteCpp#425]
SQLiteCpp with the `SQLITE_ENABLE_JSON1` #289  doesn't appear to be working. I'm using the following query to test, which returns zero.

```sql
SELECT sqlite_compileoption_used('ENABLE_JSON1')
```

I changed the line in `./build.sh` to 

```bash
cmake -DCMAKE_BUILD_TYPE=Debug -DSQLITE_ENABLE_JSON1=ON -DSQLITECPP_USE_ASAN=ON -DSQLITECPP_USE_GCOV=OFF -DSQLITECPP_BUILD_EXAMPLES=ON -DSQLITECPP_BUILD_TESTS=ON ..
```

And created a quick test in `Database_test.cpp` - which fails. for ease, you can pull it from [my fork here](https://github.com/SRombauts/SQLiteCpp/compare/master...jcurtis-cc:SQLiteCpp:json1-flag-test)

```cpp
#ifdef SQLITE_ENABLE_JSON1
TEST(Database, json1)
{
    remove("test.db3");
    {
        // Create a new database
        SQLite::Database db("test.db3", SQLite::OPEN_READWRITE | SQLite::OPEN_CREATE);
        EXPECT_FALSE(db.tableExists("test"));
        EXPECT_EQ(1, db.exec("SELECT sqlite_compileoption_used('ENABLE_JSON1')"));
    } // Close DB test.db3
    remove("test.db3");
}
#endif // SQLITE_ENABLE_JSON1
```

Any thoughts? Perhaps I'm missing something obvious here.

**Comment by SRombauts** [comment]
Hello, can you provide more details on your setup? What OS? Aka is your project really recompiling the sqlite library or using an existing one from your distribution? 

I am not in front of a computer so I cannot check the feature (coming from PR #288)

**Comment by jcurtis-cc** [comment]
Sure, MacOS 12.16 here

**Comment by SRombauts** [comment]
I think that's the reason, by default on Unixes CMake will detect the existing sqlite3 dynamic library installed in your system and use it
You want to use the cmake flag to force using the internal library built from source code

**Comment by SRombauts** [comment]
I know documentation is far from perfect, from the readme on troubleshooting:

or turn on the option(`SQLITECPP_INTERNAL_SQLITE` "Add the internal SQLite3 source to the project." ON) in [CMakeFiles.txt](https://github.com/SRombauts/SQLiteCpp/blob/master/CMakeFiles.txt)

Let me know if you have any trouble with that

**Comment by jcurtis-cc** [comment]
`option(SQLITECPP_INTERNAL_SQLITE "Add the internal SQLite3 source to the project." ON))` 

looks to be on by [default](https://github.com/SRombauts/SQLiteCpp/blob/23a16ed341b97240620ce6b25169ad0bf8dd13d9/CMakeLists.txt#LL252C86-L252C87) this is also mentioned again [here](https://github.com/SRombauts/SQLiteCpp/blob/23a16ed341b97240620ce6b25169ad0bf8dd13d9/sqlite3/README.md?plain=1#L9)

perhaps something here is overriding this:

```bash
cmake -DCMAKE_BUILD_TYPE=Debug -DSQLITE_ENABLE_JSON1=ON -DSQLITECPP_USE_ASAN=ON -DSQLITECPP_USE_GCOV=OFF -DSQLITECPP_BUILD_EXAMPLES=ON -DSQLITECPP_BUILD_TESTS=ON ..
```

**Comment by SRombauts** [comment]
I hope this helps
Cheers!
