### ISSUE TITLE
MinGW cannot find library

### ISSUE THREAD

**Issue by OMGerCoder** [SRombauts/SQLiteCpp#457]
LD pretends that the .a file doesn't exist. This only happens within my Makefile.

**Comment by ninjaoflight** [comment]
can you provide a sample repo?, currently we support CMake and Meson, but probably could guide you.

**Comment by OMGerCoder** [comment]
Oh, I fixed it. Turns out G++ (in a make environment) pretended the .a file did not exist when it was in /usr/lib.
