### ISSUE TITLE
set busy_timeout in constructor

### ISSUE THREAD

**Issue by ScottKaiGu** [SRombauts/SQLiteCpp#47]

**Comment by SRombauts** [comment]
Is Database::setBusyTimeout() not sufficient for your needs?

**Comment by ScottKaiGu** [comment]
oh, sorry didn't find it.
BTW, i have to set it every time. how about add an argument to Database's constructor?

**Comment by SRombauts** [comment]
Yes, I think setting this in the constructor is a must-have.
Python binding is doing just this!

**Comment by SRombauts** [comment]
Due tu release v1.0.0
