### ISSUE TITLE
Adding module loading support?

### ISSUE THREAD

**Issue by portwaypoint** [SRombauts/SQLiteCpp#50]
I'd like to be able to to enable module support.

In order to do this, I need to invoke this line from SQL:

SELECT load_extension('filename');

or

sqlite3_load_extension()

however this will fail until I have...

int sqlite3_enable_load_extension(sqlite3 *db, int onoff);

So, how best to add this in? I'm thinking I could either create a Utility.h with an equivalent class in the include directory, make it a friend of Database (like Statement.h) and get access to the db connection that way. 

Alternatives which don't seem so appealing are: add database connection ID accessor method (breaking the encapsulation but allowing anyone to directly use the numerous other missing calls), or add methods directly into the Database class (most of which will never be used by the majority of users). Opinions? Ideally I'd like to do this in a way that allows me to contribute back the changes.

**Comment by SRombauts** [comment]
Well, my preferred way would be to add it to Database, for the sake of
simplicity.

Cheers!

**Comment by SRombauts** [comment]
Closed thanks to PR #51
