### ISSUE TITLE
Support for string / blob data ?

### ISSUE THREAD

**Issue by aurelien35** [SRombauts/SQLiteCpp#55]
Hi,

In my application, I need to deal a lot with strings (big strings) and blob (big blob) data.

What is the current support status for these datatype in SQLiteCpp ?

Are the supported properly ? Is SQLITE_STATIC binding supported ?

Thanks.

**Comment by SRombauts** [comment]
No, those are on the TODO.txt as 'wanted features'. 

Honestly, they should be pretty easy to add to current API, but I never need them.

**Comment by SRombauts** [comment]
Implemented as of #86 Add bindNoCopy methods to allow binding std::string with SQLITE_STATIC
