### ISSUE TITLE
Log for statements

### ISSUE THREAD

**Issue by ghost** [SRombauts/SQLiteCpp#61]
Hi SRombauts,
I think it helpful to add log for sql statements, isn't it?

**Comment by SRombauts** [comment]
Hi, sorry for not answering this: this could be helpfull, but it would add some overhead I am not wiling to impose to everyone.

We could do that through optional macros.

**Comment by HighSparrow** [comment]
Hi, you are right. I added it in my own project and found it very verbose. And the codes are ugly or poor in performance.
