### ISSUE TITLE
sqlite error code info in Exception

### ISSUE THREAD

**Issue by HighSparrow** [SRombauts/SQLiteCpp#62]
Hi SRombauts,
Would it be helpful if we add sqlite error code info into SQLite::Exception?

**Comment by SRombauts** [comment]
Hi, sorry, I don't understand what you propose. Can you explain ?

**Comment by HighSparrow** [comment]
Hi,
when there is a sqlite error, it would be SQLITE_ERROR, SQLITE_ABORT, SQLITE_BUSY or SQLITE_CONSTRAINT, or something others. add error code info in exception will be helpful for error handling.

**Comment by SRombauts** [comment]
Sorry for not answering more directly, but yes this could get useful!

**Comment by NadjibR** [comment]
Yes this is what I meant in my mail. Catch only a spécific error, or send the error code to the exception block.

**Comment by SRombauts** [comment]
Implemented by @DouglasHeriot, thanks!
