### ISSUE TITLE
Build Error on VS2013 

### ISSUE THREAD

**Issue by changjurhee** [SRombauts/SQLiteCpp#63]
error MSB6006: "cmd.exe" exited with code 1.

Here is the log message for build steps. 

V:\03 git_repo\SQLiteCpp>build

V:\03 git_repo\SQLiteCpp>mkdir build
A subdirectory or file build already exists.

V:\03 git_repo\SQLiteCpp>cd build

V:\03 git_repo\SQLiteCpp\build>cmake -DSQLITECPP_BUILD_EXAMPLES=ON -DSQLITECPP_B
UILD_TESTS=ON .. -G "Visual Studio 12"
-- PYTHON_EXECUTABLE=C:/Anaconda3/python.exe
-- Could NOT find cppcheck
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
CMake Warning (dev) at CMakeLists.txt:221 (add_subdirectory):
  The source directory

    V:/03 git_repo/SQLiteCpp/googletest/CMakeLists.txt

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: V:/03 git_repo/SQLiteCpp/build

V:\03 git_repo\SQLiteCpp\build>cmake --build .
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.0]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2015-07-24 ?? 8:39:52.
Project "V:\03 git_repo\SQLiteCpp\build\ALL_BUILD.vcxproj" on node 1 (default t
argets).
Project "V:\03 git_repo\SQLiteCpp\build\ALL_BUILD.vcxproj" (1) is building "V:\
03 git_repo\SQLiteCpp\build\SQLiteCpp.vcxproj" (2) on node 1 (default targets).
Project "V:\03 git_repo\SQLiteCpp\build\SQLiteCpp.vcxproj" (2) is building "V:\
03 git_repo\SQLiteCpp\build\ZERO_CHECK.vcxproj" (3) on node 1 (default targets)
.
InitializeBuildStatus:
  Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "
  AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
  Checking Build System
  CMake does not need to re-run because V:/03 git_repo/SQLiteCpp/build/CMakeFil
  es/generate.stamp is up-to-date.
  CMake does not need to re-run because V:/03 git_repo/SQLiteCpp/build/sqlite3/
  CMakeFiles/generate.stamp is up-to-date.
  CMake does not need to re-run because V:/03 git_repo/SQLiteCpp/build/googlete
  st/CMakeFiles/generate.stamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "V:\03 git_repo\SQLiteCpp\build\ZERO_CHECK.vcxproj" (defa
ult targets).

InitializeBuildStatus:
  Creating "SQLiteCpp.dir\Debug\SQLiteCpp.tlog\unsuccessfulbuild" because "Alwa
  ysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  All outputs are up-to-date.
Lib:
  All outputs are up-to-date.
  SQLiteCpp.vcxproj -> V:\03 git_repo\SQLiteCpp\build\Debug\SQLiteCpp.lib
FinalizeBuildStatus:
  Deleting file "SQLiteCpp.dir\Debug\SQLiteCpp.tlog\unsuccessfulbuild".
  Touching "SQLiteCpp.dir\Debug\SQLiteCpp.tlog\SQLiteCpp.lastbuildstate".
Done Building Project "V:\03 git_repo\SQLiteCpp\build\SQLiteCpp.vcxproj" (defau
lt targets).

Project "V:\03 git_repo\SQLiteCpp\build\ALL_BUILD.vcxproj" (1) is building "V:\
03 git_repo\SQLiteCpp\build\SQLiteCpp_cpplint.vcxproj" (4) on node 1 (default t
argets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targe
ts(388,5): warning MSB8028: The intermediate directory (Win32\Debug\SQLiteCpp_c
pplint\) contains files shared from another project (SQLiteCpp_cpplint.vcxproj,
 SQLiteCpp_cpplint.vcxproj).  This can lead to incorrect clean and rebuild beha
vior. [V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_cpplint.vcxproj]
InitializeBuildStatus:
  Touching "Win32\Debug\SQLiteCpp_cpplint\SQLiteCp.87BFD408.tlog\unsuccessfulbu
  ild".
CustomBuild:
  Building Custom Rule V:/03 git_repo/SQLiteCpp/CMakeLists.txt
  CMake does not need to re-run because V:\03 git_repo\SQLiteCpp\build\CMakeFil
  es\generate.stamp is up-to-date.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targ
ets(170,5): error MSB6006: "cmd.exe" exited with code 1. [V:\03 git_repo\SQLite
Cpp\build\SQLiteCpp_cpplint.vcxproj]
Done Building Project "V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_cpplint.vcxproj
" (default targets) -- FAILED.

Project "V:\03 git_repo\SQLiteCpp\build\ALL_BUILD.vcxproj" (1) is building "V:\
03 git_repo\SQLiteCpp\build\SQLiteCpp_example1.vcxproj" (5) on node 1 (default
targets).
Project "V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_example1.vcxproj" (5) is buil
ding "V:\03 git_repo\SQLiteCpp\build\sqlite3\sqlite3.vcxproj" (6) on node 1 (de
fault targets).
InitializeBuildStatus:
  Creating "sqlite3.dir\Debug\sqlite3.tlog\unsuccessfulbuild" because "AlwaysCr
  eate" was specified.
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  All outputs are up-to-date.
Lib:
  All outputs are up-to-date.
  sqlite3.vcxproj -> V:\03 git_repo\SQLiteCpp\build\sqlite3\Debug\sqlite3.lib
FinalizeBuildStatus:
  Deleting file "sqlite3.dir\Debug\sqlite3.tlog\unsuccessfulbuild".
  Touching "sqlite3.dir\Debug\sqlite3.tlog\sqlite3.lastbuildstate".
Done Building Project "V:\03 git_repo\SQLiteCpp\build\sqlite3\sqlite3.vcxproj"
(default targets).

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targe
ts(388,5): warning MSB8028: The intermediate directory (SQLiteCpp_example1.dir\
Debug\) contains files shared from another project (SQLiteCpp_example1.vcxproj,
 SQLiteCpp_example1.vcxproj).  This can lead to incorrect clean and rebuild beh
avior. [V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_example1.vcxproj]
InitializeBuildStatus:
  Creating "SQLiteCpp_example1.dir\Debug\SQLiteCp.7BC30BB6.tlog\unsuccessfulbui
  ld" because "AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  All outputs are up-to-date.
Link:
  All outputs are up-to-date.
  SQLiteCpp_example1.vcxproj -> V:\03 git_repo\SQLiteCpp\build\Debug\SQLiteCpp_
  example1.exe
FinalizeBuildStatus:
  Deleting file "SQLiteCpp_example1.dir\Debug\SQLiteCp.7BC30BB6.tlog\unsuccessf
  ulbuild".
  Touching "SQLiteCpp_example1.dir\Debug\SQLiteCp.7BC30BB6.tlog\SQLiteCpp_examp
  le1.lastbuildstate".
Done Building Project "V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_example1.vcxpro
j" (default targets).

Project "V:\03 git_repo\SQLiteCpp\build\ALL_BUILD.vcxproj" (1) is building "V:\
03 git_repo\SQLiteCpp\build\SQLiteCpp_tests.vcxproj" (7) on node 1 (default tar
gets).
InitializeBuildStatus:
  Touching "SQLiteCpp_tests.dir\Debug\SQLiteCpp_tests.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /I"V:\03
   git_repo\SQLiteCpp\include" /I"V:\03 git_repo\SQLiteCpp\sqlite3" /I"V:\03 gi
  t_repo\SQLiteCpp\googletest\include" /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WI
  N32 /D _WINDOWS /D _DEBUG /D _CRT_SECURE_NO_WARNINGS /D SQLITE_ENABLE_COLUMN_
  METADATA /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MTd /GS /Zc:w
  char_t /Zc:forScope /GR /Fo"SQLiteCpp_tests.dir\Debug\\" /Fd"SQLiteCpp_tests.
  dir\Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:queue "V:\03 git_repo\SQL
  iteCpp\tests\Column_test.cpp" "V:\03 git_repo\SQLiteCpp\tests\Database_test.c
  pp" "V:\03 git_repo\SQLiteCpp\tests\Statement_test.cpp"
  Column_test.cpp
V:\03 git_repo\SQLiteCpp\tests\Column_test.cpp(16): fatal error C1083: ?? ??? ?
 ? ????. 'gtest/gtest.h': No such file or directory [V:\03 git_repo\SQLiteCpp\b
uild\SQLiteCpp_tests.vcxproj]
  Database_test.cpp
V:\03 git_repo\SQLiteCpp\tests\Database_test.cpp(14): fatal error C1083: ?? ???
 ? ? ????. 'gtest/gtest.h': No such file or directory [V:\03 git_repo\SQLiteCpp
\build\SQLiteCpp_tests.vcxproj]
  Statement_test.cpp
V:\03 git_repo\SQLiteCpp\tests\Statement_test.cpp(15): fatal error C1083: ?? ??
? ? ? ????. 'gtest/gtest.h': No such file or directory [V:\03 git_repo\SQLiteCp
p\build\SQLiteCpp_tests.vcxproj]
  ??? ???? ????...
Done Building Project "V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_tests.vcxproj"
(default targets) -- FAILED.

Done Building Project "V:\03 git_repo\SQLiteCpp\build\ALL_BUILD.vcxproj" (defau
lt targets) -- FAILED.

Build FAILED.

"V:\03 git_repo\SQLiteCpp\build\ALL_BUILD.vcxproj" (default target) (1) ->
"V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_cpplint.vcxproj" (default target) (4)
 ->
(PrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.tar
gets(388,5): warning MSB8028: The intermediate directory (Win32\Debug\SQLiteCpp
_cpplint\) contains files shared from another project (SQLiteCpp_cpplint.vcxpro
j, SQLiteCpp_cpplint.vcxproj).  This can lead to incorrect clean and rebuild be
havior. [V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_cpplint.vcxproj]

"V:\03 git_repo\SQLiteCpp\build\ALL_BUILD.vcxproj" (default target) (1) ->
"V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_example1.vcxproj" (default target) (5
) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.tar
gets(388,5): warning MSB8028: The intermediate directory (SQLiteCpp_example1.di
r\Debug\) contains files shared from another project (SQLiteCpp_example1.vcxpro
j, SQLiteCpp_example1.vcxproj).  This can lead to incorrect clean and rebuild b
ehavior. [V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_example1.vcxproj]

"V:\03 git_repo\SQLiteCpp\build\ALL_BUILD.vcxproj" (default target) (1) ->
"V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_cpplint.vcxproj" (default target) (4)
 ->
(CustomBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.ta
rgets(170,5): error MSB6006: "cmd.exe" exited with code 1. [V:\03 git_repo\SQLi
teCpp\build\SQLiteCpp_cpplint.vcxproj]

"V:\03 git_repo\SQLiteCpp\build\ALL_BUILD.vcxproj" (default target) (1) ->
"V:\03 git_repo\SQLiteCpp\build\SQLiteCpp_tests.vcxproj" (default target) (7) -
>
(ClCompile target) ->
  V:\03 git_repo\SQLiteCpp\tests\Column_test.cpp(16): fatal error C1083: ?? ???
 ? ? ????. 'gtest/gtest.h': No such file or directory [V:\03 git_repo\SQLiteCpp
\build\SQLiteCpp_tests.vcxproj]
  V:\03 git_repo\SQLiteCpp\tests\Database_test.cpp(14): fatal error C1083: ?? ?
?? ? ? ????. 'gtest/gtest.h': No such file or directory [V:\03 git_repo\SQLiteC
pp\build\SQLiteCpp_tests.vcxproj]
  V:\03 git_repo\SQLiteCpp\tests\Statement_test.cpp(15): fatal error C1083: ??
??? ? ? ????. 'gtest/gtest.h': No such file or directory [V:\03 git_repo\SQLite
Cpp\build\SQLiteCpp_tests.vcxproj]

    2 Warning(s)
    4 Error(s)

Time Elapsed 00:00:03.12

V:\03 git_repo\SQLiteCpp\build>ctest --output-on-failure
Test project V:/03 git_repo/SQLiteCpp/build
    Start 1: UnitTests
Could not find executable SQLiteCpp_tests
Looked in the following places:
SQLiteCpp_tests
SQLiteCpp_tests.exe
Release/SQLiteCpp_tests
Release/SQLiteCpp_tests.exe
Debug/SQLiteCpp_tests
Debug/SQLiteCpp_tests.exe
MinSizeRel/SQLiteCpp_tests
MinSizeRel/SQLiteCpp_tests.exe
RelWithDebInfo/SQLiteCpp_tests
RelWithDebInfo/SQLiteCpp_tests.exe
Deployment/SQLiteCpp_tests
Deployment/SQLiteCpp_tests.exe
Development/SQLiteCpp_tests
Development/SQLiteCpp_tests.exe
Unable to find executable: SQLiteCpp_tests
1/2 Test #1: UnitTests ........................***Not Run   0.00 sec
    Start 2: Example1Run
2/2 Test #2: Example1Run ......................   Passed    0.11 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   0.19 sec

The following tests FAILED:
          1 - UnitTests (Not Run)
Errors while running CTest

V:\03 git_repo\SQLiteCpp\build>cd ..

V:\03 git_repo\SQLiteCpp>

**Comment by SRombauts** [comment]
''''
    The source directory
        V:/03 git_repo/SQLiteCpp/googletest/CMakeLists.txt
    does not contain a CMakeLists.txt file.
''''

=> this is because you did not get the git submodule dependency ("git submodule init" + "git submodule update", see README or build.bat script)

Cheers
