### ISSUE TITLE
Support backup of DB file

### ISSUE THREAD

**Issue by hongshibao** [SRombauts/SQLiteCpp#70]
Hi SRombauts,
Thanks for providing this good wrapper. I find I need the backup of DB file in my application. Do you think it is necessary to add this functionality? If so, I can do some help.

**Comment by SRombauts** [comment]
Hi ! Yes, this is on my to-do list, but never used this myself. If you can provide a pull request I will be glad to review it!

**Comment by SRombauts** [comment]
Fix by #71 Support backup of DB file : thanks!
