### ISSUE TITLE
Wrong exception thrown by Database constructor

### ISSUE THREAD

**Issue by Sildra** [SRombauts/SQLiteCpp#73]
The database constructor does not return the good error message with the following code :
```cpp
SQLite::Database* db = new SQLite::Database(filename, SQLITE_OPEN_CREATE);
```

In my case it returned an out of memory message.

Can be fixed by using `sqlite3_errstr()` instead of `sqlite3_errmsg()`.

**Comment by SRombauts** [comment]
Hum, problem is that sqlite3_errstr() is availlable only on recent Linux distributions, not in the one used for continuous integration testing ; will need some #ifdef

**Comment by SRombauts** [comment]
Thanks for reporting this!
