### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by rajko-d** [SRombauts/SQLiteCpp#75]
Do I have to declare  SQLite::Database db("test.db") every time I want to use database? Is there any static function which gets default database when I construct it first time when program starts. Sorry if I'm not precise enaugh.After several minutes of thinking I suppose I can write it myself :). Please consider this post closed.

**Comment by SRombauts** [comment]
Hi! Well, in general opening a Database is synonym of opening an existing data file of an application (a SQLite3 *.db3 file). Some application have only one central db3 file, others use many of them.
Thus, in those cases there is no meaning of a "default" Database...

If what you want is "open the unique Database once and use this unique connection everywhere", then you could, for instance, use the design pattern "Singleton" to share the connection across your whole application (a Singleton gives you a unique instance with a static interface).

But sometimes you don't really want to open a file, then you can open a "in memory" Database, but then you still can name it as you like, so there is no real "default one".

Is this clear enough?

Cheers!

**Comment by rajko-d** [comment]
Thanks.

**Comment by nyckmaia** [comment]
@SRombauts how can I create a "in memory" database?

**Comment by nyckmaia** [comment]
I found in your `example01`...thanks!
