### ISSUE TITLE
Occasional "database is locked" exception when multiple threads access the same database.

### ISSUE THREAD

**Issue by mahl** [SRombauts/SQLiteCpp#77]
We got "database is locked" exceptions sometimes when multiple threads insert into the same table in a database. We are not sharing the SQLite::Database object among threads. Each thread will create its own SQLite::Database object. The Multi-thread mode is already used. Basically our code is like:
~~~
void insertToDb(int value)
{
  SQLite::Database db(_dbPath, SQLITE_OPEN_READWRITE|SQLITE_OPEN_NOMUTEX);
  SQLite::Statement query(db,
			"INSERT INTO record"
			"(a) "
			"VALUES (?,");
  query.bind(1, value);
  query.exec();
}
~~~

Each thread will call this method to insert into the database. Autoincrement Id is used in the table.

**Comment by SRombauts** [comment]
Hi, Yes, this is the universal problem of SQLite : you should never edit a database simultaneously from multiple threads, it is not designed to do this.

You have to serialize your edits, for instance using a fifo with a unique writer thread.

**Comment by SRombauts** [comment]
Please have a look to online resources on thoses difficult problems, for instance using busy handlers.

See http://www.sqlite.org/cvstrac/wiki?p=MultiThreading
