### ISSUE TITLE
Integration with Visual Studio 2015

### ISSUE THREAD

**Issue by DZoki019** [SRombauts/SQLiteCpp#79]
I want to use this library in my (Visual Studio) project, but i dont understand how to include it. Any help?

**Comment by SRombauts** [comment]
Hi, easiest way to integrate the code if you don't know anything about CMake would be to:
1. copy the source files on a directory
2. then in Visual Studio "Add existing files" to your project

**Comment by DZoki019** [comment]
Thanks a lot. I should learn more about CMake.
