### ISSUE TITLE
Sqlite errors

### ISSUE THREAD

**Issue by Aykelith** [SRombauts/SQLiteCpp#82]
I'm receiving this error, using `g++ (i686-posix-dwarf-rev1, Built by MinGW-W64 project) 4.9.2`

> /mingw492/SQLiteCpp/sqlite3/libsqlite3.a(sqlite3.c.obj):sqlite3.c:(.text+0x7a8f4): undefined reference to `__stack_chk_guard'
/mingw492/SQLiteCpp/sqlite3/libsqlite3.a(sqlite3.c.obj):sqlite3.c:(.text+0x7a8fb): undefined reference to `__stack_chk_fail'

**Comment by SRombauts** [comment]
Hi, 

This looks like a problem with sqlite3, not with the wrapper. 

Can you look if you have it with a previous version of my wrapper (because I updated the sqlite3 recently)?

**Comment by Aykelith** [comment]
Tried with the last update, same problem.

**Comment by SRombauts** [comment]
No, I would like to know if you can try with a "previous version" (older one) of sqlite3 or of the SQLiteCpp wrapper to see if this is a recent issue.

**Comment by SRombauts** [comment]
Other thing to try, after googling your error message ([undefined-reference-to-stack-chk-fail](http://stackoverflow.com/questions/4492799/undefined-reference-to-stack-chk-fail)):
try to remove the flag [-fstack-protector on the CMakeLists.txt file of SQLiteCpp (line 33)](https://github.com/SRombauts/SQLiteCpp/blob/master/CMakeLists.txt#L33).

**Comment by Aykelith** [comment]
Thanks, it worked.

**Comment by SRombauts** [comment]
You are welcome!
