### ISSUE TITLE
Compile issue on armv5 linux

### ISSUE THREAD

**Issue by MrDini123** [SRombauts/SQLiteCpp#83]
Hi!

I tried to compile the SQLiteCpp on my nas, but it says something like this, when I try to build (make) it:

```
# cmake --build ./
Scanning dependencies of target SQLiteCpp
[ 16%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Column.cpp.o
[ 33%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Database.cpp.o
[ 50%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Statement.cpp.o
[ 66%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Transaction.cpp.o
[ 83%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o
Linking CXX static library libSQLiteCpp.a
[ 83%] Built target SQLiteCpp
Scanning dependencies of target SQLiteCpp_cpplint
CMakeFiles/SQLiteCpp_cpplint.dir/build.make:49: recipe for target 'CMakeFiles/SQLiteCpp_cpplint' failed
make[2]: *** [CMakeFiles/SQLiteCpp_cpplint] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/SQLiteCpp_cpplint.dir/all' failed
make[1]: *** [CMakeFiles/SQLiteCpp_cpplint.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
```

My nas has an old armv5tel based processor and an old kernel (2.6.31.8) but it works nice with same cmake based sources.

Thanks for UR answer!

**Comment by SRombauts** [comment]
Hi,

I don't know why exactly this happens, but it is related to the "cpplint" task that is generated it you have Python installed.

cpplint is a static code source analyser (by Google)
=> this is only useful for development so you can just turn it of by passing -DSQLITECPP_RUN_CPPLINT=OFF to the cmake command line (at generation time)
(You can have a look to [the build.sh script](build.sh) if you want to see how to pass arguments to cmake) 

Tell me if this works for you,
Cheers!

**Comment by MrDini123** [comment]
Thanks a lot man!

It solved the problem and saved my life! :)

I have a noob question, So sorry for that, but I Can't found any article or blog article about that. So how Can I install it after the "cmake --build ./"?

Ps: UR link with the build.sh gives me a 404, not found error.
