### ISSUE TITLE
Build as MinGW?

### ISSUE THREAD

**Issue by kassane** [SRombauts/SQLiteCpp#88]
Hello, how are you?

I would like to know how to build it using only the MinGW?

thx!

**Comment by SRombauts** [comment]
Hi @kassane,

are you looking for building with MinGW on Windows, or crosscompiling under Linux?

Cheers!

**Comment by kassane** [comment]
Windows!

**Comment by Alexhuszagh** [comment]
@kassane It works using MSYS (MinGW in a DLL-based Cygwin-like shell, but allows for distributable executables) with the following directions:

First, open "CMakeLists.txt" and comment out all the CPPLint lines.

```
cmake .. -G"MSYS Makefiles"
make
```

I'm assuming the same should also work in a standard MinGW build environment, only swapping "MSYS Makefiles" with "MinGW Makefiles".

Best of luck.

**Comment by SRombauts** [comment]
you don't need to modify the CMakeLists.txt you can use the SQLITECPP_RUN_CPPLINT option like this:

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -SQLITECPP_RUN_CPPLINT=OFF -DSQLITECPP_USE_GCOV=OFF -DSQLITECPP_BUILD_EXAMPLES=OFF -DSQLITECPP_BUILD_TESTS=OFF .. - G "MinGW Makefiles" 
make

**Comment by Alexhuszagh** [comment]
@SRombauts Ah thank you, my mistake.

**Comment by kassane** [comment]
@SRombauts thx, but help fix it:

`Scanning dependencies of target SQLiteCpp
[ 12%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Column.cpp.obj
[ 25%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Database.cpp.obj
[ 37%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Statement.cpp.obj
[ 50%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Transaction.cpp.obj
[ 62%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.obj
[ 75%] Linking CXX static library libSQLiteCpp.a
[ 75%] Built target SQLiteCpp
Scanning dependencies of target SQLiteCpp_cpplint
CMakeFiles\SQLiteCpp_cpplint.dir\build.make:56: recipe for target 'CMakeFiles/SQLiteCpp_cpplint' failed
CMakeFiles\Makefile2:103: recipe for target 'CMakeFiles/SQLiteCpp_cpplint.dir/all' failed
Makefile:82: recipe for target 'all' failed
`
