### ISSUE TITLE
Why forced static runtime on MSVC?

### ISSUE THREAD

**Issue by giumas** [SRombauts/SQLiteCpp#92]
As in the title, I would like to understand the compelling reason to force a static runtime for the library (https://github.com/SRombauts/SQLiteCpp/blob/master/CMakeLists.txt#L24).  

This is an issue for any project that wants to use `SQLiteCpp`, but also has to link to shared libraries (e.g., LGPL). Additional information in this SO answer: http://stackoverflow.com/a/4307551/2741329

I believe that a possible solution would be to adopt a CMake option similar to what `gtest` provides (i.e., `gtest_force_shared_crt`), so that user can decide the kind of runtime.
Incidentally, such an approach might also solve https://github.com/SRombauts/SQLiteCpp/issues/53 without the need to add the export decorations as proposed in https://github.com/SRombauts/SQLiteCpp/pull/57.

**Comment by SRombauts** [comment]
You are right, static runtime is only required/recommended by googletest, so I should force it only in coordination with unit tests.

**Comment by SRombauts** [comment]
Hi @giumas, the fix I implemented is only the simplest option of all, that is, I know force the use of static runtime only when Unit Tests are enabled (which is OFF by default in the CMakeLists.txt).

If this does not suit your needs, please let me know.

Cheers!

**Comment by giumas** [comment]
The changes solved my issue, so I don't need anymore to tweak the library's CMake. 

Thank for having been so responsive!

**Comment by SRombauts** [comment]
Nice! 

Also, you can propose any other changes as Pull Requests if you wish. 

Cheers

**Comment by SRombauts** [comment]
CMakeFiles.txt updated to not force static runtime anymore #438
