### ISSUE TITLE
Colliding definition of conversion functions in Column

### ISSUE THREAD

**Issue by jmgao** [SRombauts/SQLiteCpp#93]
The guards around the conversion functions starting [here](https://github.com/SRombauts/SQLiteCpp/blob/master/include/SQLiteCpp/Column.h#L174) seem to be incorrect, leading to colliding definitions on non-apple, non-x86_64 platforms that typedef int64_t to long. (e.g. arm64 android/glibc linux). (This is only visible under clang, because of [a gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71919) that allows redefinition of user-defined conversion functions, as long as they're all inline).

Defining conversion functions for int64_t and uint32_t alongside conversions for int/long/long long also seems a bit sketchy.

Perhaps something along the lines of the following would work?
```
inline operator int() {
    return getInt();
}

inline operator long() {
#if sizeof(long) == 8
    return getInt64();
#else
    return getInt();
#endif
}

inline operator long long() {
    return getInt64();
}

inline operator unsigned() {
    return getUInt();
}

#if sizeof(unsigned long) == 4
inline operator unsigned long() {
    return getUInt();
}
#endif
```

(original report from https://github.com/android-ndk/ndk/issues/163)

**Comment by SRombauts** [comment]
Hi @jmgao, thanks for the detailed report (and thanks to @4brunu)

I will sure look into this issue and your proposed solution!

**Comment by SRombauts** [comment]
Thanks again @jmgao, and please @4brunu, let me know if this actually works in your use case!

**Comment by 4brunu** [comment]
It works, thanks a lot @jmgao and @SRombauts for the help.

**Comment by SRombauts** [comment]
Good to hear, thanks!
