### ISSUE TITLE
x64 Support?

### ISSUE THREAD

**Issue by DJLectr0** [SRombauts/SQLiteCpp#98]
I was wondering how I could build this library for 64bit. I need this, as my project is 64bit only.

**Comment by DJLectr0** [comment]
Nevermind, I found it out:

    mkdir build64
    cd build64
    cmake -G "Visual Studio 12 2013 Win64" ..

**Comment by SRombauts** [comment]
Nice to hear, I would have answer the same, but a few hours later. 

Cheers!
