### ISSUE TITLE
Project doesn't build on arch linux.

### ISSUE THREAD

**Issue by Single34** [SRombauts/SQLiteCpp#99]
Project doesn't build on arch linux.

Arch linux uses python3 as default python interpreter. But cpplint.py seems to require python2. Although running it without any parameter it will print out help message happily but when used with parameters it will crash without any message.

you should add something in the CMakelists.txt, perhaps before find_package(PythonInterp).

**Comment by SRombauts** [comment]
Good catch, I could check python version, or update cpplint. 
Thanks!
